/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Modelo.*;
import java.awt.Color;
import java.util.UUID;
import javax.swing.Icon;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis Bizarro
 */
public class AgregadoDeCremas extends javax.swing.JFrame {
    private DetallePedido detallePedidoActual;
    private Pedido pedidoActual;
    private int salsasAgregadas = 0;
    private final double COSTO_SALSA_EXTRA = 1.0;
    int xMouse, yMouse;
    
    public AgregadoDeCremas() {
        initComponents();
        this.setLocationRelativeTo(null);
        pedidoActual = null;
    }

    public AgregadoDeCremas(Producto producto, Icon icono) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.detallePedidoActual = new DetallePedido(producto, 1);
        jDescripcion.setText(producto.getNombre());
        jPrecio.setText(String.valueOf(producto.getPrecio()));
        lblImagenPedido.setIcon(icono);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        barraMovedora = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();
        panelExit = new javax.swing.JPanel();
        panelInicio = new javax.swing.JPanel();
        lblInicio = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        lblMenu = new javax.swing.JLabel();
        panelOrden = new javax.swing.JPanel();
        lblOrden = new javax.swing.JLabel();
        panelListaDeOrdenes = new javax.swing.JPanel();
        lblListaDeOrdenes = new javax.swing.JLabel();
        panelIniciarSesion = new javax.swing.JPanel();
        lblIniciarSesion = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelRound1 = new vista.PanelRound();
        jLabel4 = new javax.swing.JLabel();
        panelRound2 = new vista.PanelRound();
        lblImagenPedido = new javax.swing.JLabel();
        jDescripcion = new javax.swing.JLabel();
        jPrecio = new javax.swing.JLabel();
        panelRound3 = new vista.PanelRound();
        jLabel7 = new javax.swing.JLabel();
        infoMayonesa = new javax.swing.JLabel();
        panelAgregarOtra = new vista.PanelRound();
        labelAgregarOtra1 = new javax.swing.JLabel();
        panelRound12 = new vista.PanelRound();
        verTicket = new javax.swing.JLabel();
        panelRound11 = new vista.PanelRound();
        panelRound16 = new vista.PanelRound();
        mayonesaAdd = new javax.swing.JLabel();
        panelRound4 = new vista.PanelRound();
        jLabel12 = new javax.swing.JLabel();
        infoKetchup = new javax.swing.JLabel();
        panelRound5 = new vista.PanelRound();
        jLabel14 = new javax.swing.JLabel();
        infoAji = new javax.swing.JLabel();
        panelRound6 = new vista.PanelRound();
        jLabel16 = new javax.swing.JLabel();
        infoGolf = new javax.swing.JLabel();
        panelRound13 = new vista.PanelRound();
        ketchupAdd = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        panelRound14 = new vista.PanelRound();
        ajiAdd = new javax.swing.JLabel();
        panelRound15 = new vista.PanelRound();
        golfAdd = new javax.swing.JLabel();
        panelRound7 = new vista.PanelRound();
        jLabel21 = new javax.swing.JLabel();
        infoMostaza = new javax.swing.JLabel();
        panelRound8 = new vista.PanelRound();
        jLabel23 = new javax.swing.JLabel();
        infoTartara = new javax.swing.JLabel();
        panelRound17 = new vista.PanelRound();
        mostazaAdd = new javax.swing.JLabel();
        panelRound18 = new vista.PanelRound();
        tartaraAdd = new javax.swing.JLabel();
        panelRound19 = new vista.PanelRound();
        bbqAdd = new javax.swing.JLabel();
        panelRound20 = new vista.PanelRound();
        chimichurriAdd = new javax.swing.JLabel();
        panelRound9 = new vista.PanelRound();
        jLabel25 = new javax.swing.JLabel();
        infoBBQ = new javax.swing.JLabel();
        panelRound10 = new vista.PanelRound();
        jLabel27 = new javax.swing.JLabel();
        infoChimi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(160, 3, 23));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/logoCocosBurger.png"))); // NOI18N
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        barraMovedora.setBackground(new java.awt.Color(160, 3, 23));
        barraMovedora.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraMovedoraMouseDragged(evt);
            }
        });
        barraMovedora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraMovedoraMousePressed(evt);
            }
        });

        javax.swing.GroupLayout barraMovedoraLayout = new javax.swing.GroupLayout(barraMovedora);
        barraMovedora.setLayout(barraMovedoraLayout);
        barraMovedoraLayout.setHorizontalGroup(
            barraMovedoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        barraMovedoraLayout.setVerticalGroup(
            barraMovedoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        bg.add(barraMovedora, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 30));

        lblExit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setText("x");
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });
        bg.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 40, 40));

        panelExit.setBackground(new java.awt.Color(160, 3, 23));

        javax.swing.GroupLayout panelExitLayout = new javax.swing.GroupLayout(panelExit);
        panelExit.setLayout(panelExitLayout);
        panelExitLayout.setHorizontalGroup(
            panelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        panelExitLayout.setVerticalGroup(
            panelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        bg.add(panelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 40, 40));

        panelInicio.setBackground(new java.awt.Color(160, 3, 23));

        lblInicio.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        lblInicio.setForeground(new java.awt.Color(255, 255, 255));
        lblInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInicio.setText("Inicio");
        lblInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblInicioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelInicioLayout = new javax.swing.GroupLayout(panelInicio);
        panelInicio.setLayout(panelInicioLayout);
        panelInicioLayout.setHorizontalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        panelInicioLayout.setVerticalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        bg.add(panelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 90, 50));

        panelMenu.setBackground(new java.awt.Color(160, 3, 23));

        lblMenu.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        lblMenu.setForeground(new java.awt.Color(255, 255, 255));
        lblMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenu.setText("Menu");
        lblMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMenuMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 100, -1));

        panelOrden.setBackground(new java.awt.Color(160, 3, 23));

        lblOrden.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        lblOrden.setForeground(new java.awt.Color(255, 255, 255));
        lblOrden.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrden.setText("Orden");
        lblOrden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOrdenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblOrdenMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelOrdenLayout = new javax.swing.GroupLayout(panelOrden);
        panelOrden.setLayout(panelOrdenLayout);
        panelOrdenLayout.setHorizontalGroup(
            panelOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblOrden, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        panelOrdenLayout.setVerticalGroup(
            panelOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOrdenLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(panelOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 110, -1));

        panelListaDeOrdenes.setBackground(new java.awt.Color(160, 3, 23));

        lblListaDeOrdenes.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        lblListaDeOrdenes.setForeground(new java.awt.Color(255, 255, 255));
        lblListaDeOrdenes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblListaDeOrdenes.setText("Lista de ordenes");
        lblListaDeOrdenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblListaDeOrdenesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblListaDeOrdenesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelListaDeOrdenesLayout = new javax.swing.GroupLayout(panelListaDeOrdenes);
        panelListaDeOrdenes.setLayout(panelListaDeOrdenesLayout);
        panelListaDeOrdenesLayout.setHorizontalGroup(
            panelListaDeOrdenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblListaDeOrdenes, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        panelListaDeOrdenesLayout.setVerticalGroup(
            panelListaDeOrdenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelListaDeOrdenesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblListaDeOrdenes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(panelListaDeOrdenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 190, -1));

        panelIniciarSesion.setBackground(new java.awt.Color(160, 3, 23));

        lblIniciarSesion.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        lblIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        lblIniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIniciarSesion.setText("Iniciar sesión");
        lblIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIniciarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIniciarSesionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelIniciarSesionLayout = new javax.swing.GroupLayout(panelIniciarSesion);
        panelIniciarSesion.setLayout(panelIniciarSesionLayout);
        panelIniciarSesionLayout.setHorizontalGroup(
            panelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        panelIniciarSesionLayout.setVerticalGroup(
            panelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIniciarSesionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(panelIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, 150, -1));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 1, 60)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Coco's");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Burguer");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        panelRound1.setBackground(new java.awt.Color(36, 35, 41));
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Seleccionada");
        panelRound1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        panelRound2.setBackground(new java.awt.Color(36, 35, 41));
        panelRound2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 102)));
        panelRound2.setRoundBottomLeft(20);
        panelRound2.setRoundBottomRight(20);
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);

        lblImagenPedido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagenPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagenPedidoMouseClicked(evt);
            }
        });

        jDescripcion.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        jDescripcion.setText("Descripcion");

        jPrecio.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jPrecio.setForeground(new java.awt.Color(255, 255, 255));
        jPrecio.setText("Precio");

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagenPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagenPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelRound1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, 230));

        panelRound3.setBackground(new java.awt.Color(47, 46, 52));
        panelRound3.setRoundBottomLeft(25);
        panelRound3.setRoundBottomRight(25);
        panelRound3.setRoundTopLeft(25);
        panelRound3.setRoundTopRight(25);

        jLabel7.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Mayonesa");

        infoMayonesa.setForeground(new java.awt.Color(255, 255, 255));
        infoMayonesa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoMayonesa.setText("0");

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
            .addComponent(infoMayonesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(infoMayonesa))
        );

        panelRound1.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 150, 40));

        panelAgregarOtra.setBackground(new java.awt.Color(226, 151, 29));
        panelAgregarOtra.setRoundBottomLeft(25);
        panelAgregarOtra.setRoundBottomRight(25);
        panelAgregarOtra.setRoundTopLeft(25);
        panelAgregarOtra.setRoundTopRight(25);

        labelAgregarOtra1.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        labelAgregarOtra1.setForeground(new java.awt.Color(255, 255, 255));
        labelAgregarOtra1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAgregarOtra1.setText("Añadir otra");
        labelAgregarOtra1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelAgregarOtra1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAgregarOtra1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelAgregarOtraLayout = new javax.swing.GroupLayout(panelAgregarOtra);
        panelAgregarOtra.setLayout(panelAgregarOtraLayout);
        panelAgregarOtraLayout.setHorizontalGroup(
            panelAgregarOtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelAgregarOtra1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        panelAgregarOtraLayout.setVerticalGroup(
            panelAgregarOtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelAgregarOtra1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelRound1.add(panelAgregarOtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 180, 30));

        panelRound12.setBackground(new java.awt.Color(166, 74, 160));
        panelRound12.setRoundBottomLeft(25);
        panelRound12.setRoundBottomRight(25);
        panelRound12.setRoundTopLeft(25);
        panelRound12.setRoundTopRight(25);

        verTicket.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        verTicket.setForeground(new java.awt.Color(255, 255, 255));
        verTicket.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        verTicket.setText("Ver ticket");
        verTicket.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verTicket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verTicketMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound12Layout = new javax.swing.GroupLayout(panelRound12);
        panelRound12.setLayout(panelRound12Layout);
        panelRound12Layout.setHorizontalGroup(
            panelRound12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(verTicket, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        panelRound12Layout.setVerticalGroup(
            panelRound12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(verTicket, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelRound1.add(panelRound12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 190, -1));

        panelRound11.setBackground(new java.awt.Color(71, 45, 51));
        panelRound11.setRoundBottomLeft(100);
        panelRound11.setRoundBottomRight(100);
        panelRound11.setRoundTopLeft(100);
        panelRound11.setRoundTopRight(100);

        panelRound16.setBackground(new java.awt.Color(71, 45, 51));
        panelRound16.setRoundBottomLeft(100);
        panelRound16.setRoundBottomRight(100);
        panelRound16.setRoundTopLeft(100);
        panelRound16.setRoundTopRight(100);

        mayonesaAdd.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        mayonesaAdd.setForeground(new java.awt.Color(255, 255, 255));
        mayonesaAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mayonesaAdd.setText("+");
        mayonesaAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mayonesaAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mayonesaAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound16Layout = new javax.swing.GroupLayout(panelRound16);
        panelRound16.setLayout(panelRound16Layout);
        panelRound16Layout.setHorizontalGroup(
            panelRound16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound16Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mayonesaAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelRound16Layout.setVerticalGroup(
            panelRound16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound16Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mayonesaAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panelRound11Layout = new javax.swing.GroupLayout(panelRound11);
        panelRound11.setLayout(panelRound11Layout);
        panelRound11Layout.setHorizontalGroup(
            panelRound11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound11Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelRound16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelRound11Layout.setVerticalGroup(
            panelRound11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound11Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelRound16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelRound1.add(panelRound11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 40, 40));

        panelRound4.setBackground(new java.awt.Color(47, 46, 52));
        panelRound4.setRoundBottomLeft(25);
        panelRound4.setRoundBottomRight(25);
        panelRound4.setRoundTopLeft(25);
        panelRound4.setRoundTopRight(25);

        jLabel12.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Ketchup");

        infoKetchup.setForeground(new java.awt.Color(255, 255, 255));
        infoKetchup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoKetchup.setText("0");

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
            .addComponent(infoKetchup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(infoKetchup))
        );

        panelRound1.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, -1));

        panelRound5.setBackground(new java.awt.Color(47, 46, 52));
        panelRound5.setRoundBottomLeft(25);
        panelRound5.setRoundBottomRight(25);
        panelRound5.setRoundTopLeft(25);
        panelRound5.setRoundTopRight(25);

        jLabel14.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Ají");

        infoAji.setForeground(new java.awt.Color(255, 255, 255));
        infoAji.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoAji.setText("0");

        javax.swing.GroupLayout panelRound5Layout = new javax.swing.GroupLayout(panelRound5);
        panelRound5.setLayout(panelRound5Layout);
        panelRound5Layout.setHorizontalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(infoAji, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        panelRound5Layout.setVerticalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound5Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(infoAji))
        );

        panelRound1.add(panelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 150, 40));

        panelRound6.setBackground(new java.awt.Color(47, 46, 52));
        panelRound6.setRoundBottomLeft(25);
        panelRound6.setRoundBottomRight(25);
        panelRound6.setRoundTopLeft(25);
        panelRound6.setRoundTopRight(25);

        jLabel16.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Golf");

        infoGolf.setForeground(new java.awt.Color(255, 255, 255));
        infoGolf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoGolf.setText("0");

        javax.swing.GroupLayout panelRound6Layout = new javax.swing.GroupLayout(panelRound6);
        panelRound6.setLayout(panelRound6Layout);
        panelRound6Layout.setHorizontalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(infoGolf, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        panelRound6Layout.setVerticalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound6Layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(infoGolf))
        );

        panelRound1.add(panelRound6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 150, 40));

        panelRound13.setBackground(new java.awt.Color(71, 45, 51));
        panelRound13.setRoundBottomLeft(100);
        panelRound13.setRoundBottomRight(100);
        panelRound13.setRoundTopLeft(100);
        panelRound13.setRoundTopRight(100);

        ketchupAdd.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        ketchupAdd.setForeground(new java.awt.Color(255, 255, 255));
        ketchupAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ketchupAdd.setText("+");
        ketchupAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ketchupAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ketchupAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound13Layout = new javax.swing.GroupLayout(panelRound13);
        panelRound13.setLayout(panelRound13Layout);
        panelRound13Layout.setHorizontalGroup(
            panelRound13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound13Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ketchupAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelRound13Layout.setVerticalGroup(
            panelRound13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound13Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ketchupAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelRound1.add(panelRound13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("+");
        panelRound1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 40, 40));

        panelRound14.setBackground(new java.awt.Color(71, 45, 51));
        panelRound14.setRoundBottomLeft(100);
        panelRound14.setRoundBottomRight(100);
        panelRound14.setRoundTopLeft(100);
        panelRound14.setRoundTopRight(100);

        ajiAdd.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        ajiAdd.setForeground(new java.awt.Color(255, 255, 255));
        ajiAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ajiAdd.setText("+");
        ajiAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ajiAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajiAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound14Layout = new javax.swing.GroupLayout(panelRound14);
        panelRound14.setLayout(panelRound14Layout);
        panelRound14Layout.setHorizontalGroup(
            panelRound14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound14Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ajiAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelRound14Layout.setVerticalGroup(
            panelRound14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound14Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ajiAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelRound1.add(panelRound14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, -1));

        panelRound15.setBackground(new java.awt.Color(71, 45, 51));
        panelRound15.setRoundBottomLeft(100);
        panelRound15.setRoundBottomRight(100);
        panelRound15.setRoundTopLeft(100);
        panelRound15.setRoundTopRight(100);

        golfAdd.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        golfAdd.setForeground(new java.awt.Color(255, 255, 255));
        golfAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        golfAdd.setText("+");
        golfAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        golfAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                golfAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound15Layout = new javax.swing.GroupLayout(panelRound15);
        panelRound15.setLayout(panelRound15Layout);
        panelRound15Layout.setHorizontalGroup(
            panelRound15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound15Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(golfAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelRound15Layout.setVerticalGroup(
            panelRound15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound15Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(golfAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelRound1.add(panelRound15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, -1, -1));

        panelRound7.setBackground(new java.awt.Color(47, 46, 52));
        panelRound7.setRoundBottomLeft(25);
        panelRound7.setRoundBottomRight(25);
        panelRound7.setRoundTopLeft(25);
        panelRound7.setRoundTopRight(25);

        jLabel21.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Mostaza");

        infoMostaza.setForeground(new java.awt.Color(255, 255, 255));
        infoMostaza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoMostaza.setText("0");

        javax.swing.GroupLayout panelRound7Layout = new javax.swing.GroupLayout(panelRound7);
        panelRound7.setLayout(panelRound7Layout);
        panelRound7Layout.setHorizontalGroup(
            panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
            .addComponent(infoMostaza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelRound7Layout.setVerticalGroup(
            panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound7Layout.createSequentialGroup()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(infoMostaza))
        );

        panelRound1.add(panelRound7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 150, 40));

        panelRound8.setBackground(new java.awt.Color(47, 46, 52));
        panelRound8.setRoundBottomLeft(25);
        panelRound8.setRoundBottomRight(25);
        panelRound8.setRoundTopLeft(25);
        panelRound8.setRoundTopRight(25);

        jLabel23.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Tartara");

        infoTartara.setForeground(new java.awt.Color(255, 255, 255));
        infoTartara.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoTartara.setText("0");

        javax.swing.GroupLayout panelRound8Layout = new javax.swing.GroupLayout(panelRound8);
        panelRound8.setLayout(panelRound8Layout);
        panelRound8Layout.setHorizontalGroup(
            panelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
            .addComponent(infoTartara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelRound8Layout.setVerticalGroup(
            panelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound8Layout.createSequentialGroup()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(infoTartara))
        );

        panelRound1.add(panelRound8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 150, 40));

        panelRound17.setBackground(new java.awt.Color(71, 45, 51));
        panelRound17.setRoundBottomLeft(100);
        panelRound17.setRoundBottomRight(100);
        panelRound17.setRoundTopLeft(100);
        panelRound17.setRoundTopRight(100);

        mostazaAdd.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        mostazaAdd.setForeground(new java.awt.Color(255, 255, 255));
        mostazaAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mostazaAdd.setText("+");
        mostazaAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mostazaAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostazaAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound17Layout = new javax.swing.GroupLayout(panelRound17);
        panelRound17.setLayout(panelRound17Layout);
        panelRound17Layout.setHorizontalGroup(
            panelRound17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound17Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mostazaAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelRound17Layout.setVerticalGroup(
            panelRound17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound17Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mostazaAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelRound1.add(panelRound17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, -1, -1));

        panelRound18.setBackground(new java.awt.Color(71, 45, 51));
        panelRound18.setRoundBottomLeft(100);
        panelRound18.setRoundBottomRight(100);
        panelRound18.setRoundTopLeft(100);
        panelRound18.setRoundTopRight(100);

        tartaraAdd.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        tartaraAdd.setForeground(new java.awt.Color(255, 255, 255));
        tartaraAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tartaraAdd.setText("+");
        tartaraAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tartaraAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tartaraAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound18Layout = new javax.swing.GroupLayout(panelRound18);
        panelRound18.setLayout(panelRound18Layout);
        panelRound18Layout.setHorizontalGroup(
            panelRound18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound18Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tartaraAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelRound18Layout.setVerticalGroup(
            panelRound18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound18Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tartaraAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelRound1.add(panelRound18, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, -1, -1));

        panelRound19.setBackground(new java.awt.Color(71, 45, 51));
        panelRound19.setRoundBottomLeft(100);
        panelRound19.setRoundBottomRight(100);
        panelRound19.setRoundTopLeft(100);
        panelRound19.setRoundTopRight(100);

        bbqAdd.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        bbqAdd.setForeground(new java.awt.Color(255, 255, 255));
        bbqAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bbqAdd.setText("+");
        bbqAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bbqAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bbqAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound19Layout = new javax.swing.GroupLayout(panelRound19);
        panelRound19.setLayout(panelRound19Layout);
        panelRound19Layout.setHorizontalGroup(
            panelRound19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound19Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bbqAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelRound19Layout.setVerticalGroup(
            panelRound19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound19Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bbqAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelRound1.add(panelRound19, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, -1, -1));

        panelRound20.setBackground(new java.awt.Color(71, 45, 51));
        panelRound20.setRoundBottomLeft(100);
        panelRound20.setRoundBottomRight(100);
        panelRound20.setRoundTopLeft(100);
        panelRound20.setRoundTopRight(100);

        chimichurriAdd.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        chimichurriAdd.setForeground(new java.awt.Color(255, 255, 255));
        chimichurriAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chimichurriAdd.setText("+");
        chimichurriAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chimichurriAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chimichurriAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound20Layout = new javax.swing.GroupLayout(panelRound20);
        panelRound20.setLayout(panelRound20Layout);
        panelRound20Layout.setHorizontalGroup(
            panelRound20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound20Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(chimichurriAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelRound20Layout.setVerticalGroup(
            panelRound20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound20Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(chimichurriAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelRound1.add(panelRound20, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, -1, -1));

        panelRound9.setBackground(new java.awt.Color(47, 46, 52));
        panelRound9.setRoundBottomLeft(25);
        panelRound9.setRoundBottomRight(25);
        panelRound9.setRoundTopLeft(25);
        panelRound9.setRoundTopRight(25);

        jLabel25.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Salsa BBQ");

        infoBBQ.setForeground(new java.awt.Color(255, 255, 255));
        infoBBQ.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoBBQ.setText("0");

        javax.swing.GroupLayout panelRound9Layout = new javax.swing.GroupLayout(panelRound9);
        panelRound9.setLayout(panelRound9Layout);
        panelRound9Layout.setHorizontalGroup(
            panelRound9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
            .addComponent(infoBBQ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelRound9Layout.setVerticalGroup(
            panelRound9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound9Layout.createSequentialGroup()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(infoBBQ))
        );

        panelRound1.add(panelRound9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 150, 40));

        panelRound10.setBackground(new java.awt.Color(47, 46, 52));
        panelRound10.setRoundBottomLeft(25);
        panelRound10.setRoundBottomRight(25);
        panelRound10.setRoundTopLeft(25);
        panelRound10.setRoundTopRight(25);

        jLabel27.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Chimichurri");

        infoChimi.setForeground(new java.awt.Color(255, 255, 255));
        infoChimi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoChimi.setText("0");

        javax.swing.GroupLayout panelRound10Layout = new javax.swing.GroupLayout(panelRound10);
        panelRound10.setLayout(panelRound10Layout);
        panelRound10Layout.setHorizontalGroup(
            panelRound10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
            .addComponent(infoChimi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelRound10Layout.setVerticalGroup(
            panelRound10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound10Layout.createSequentialGroup()
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(infoChimi))
        );

        panelRound1.add(panelRound10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 150, 40));

        bg.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 680, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barraMovedoraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraMovedoraMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
           
    }//GEN-LAST:event_barraMovedoraMousePressed

    private void barraMovedoraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraMovedoraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_barraMovedoraMouseDragged

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        // TODO add your handling code here:
        panelExit.setBackground(new Color(251,40,67));
        lblExit.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        panelExit.setBackground(new Color(160,3,23));
        lblExit.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lblExitMouseExited

    private void lblInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInicioMouseEntered
        panelInicio.setBackground(new Color(108,2,16));
        lblInicio.setForeground(new Color(254,194,169));
    }//GEN-LAST:event_lblInicioMouseEntered

    private void lblInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInicioMouseExited
        panelInicio.setBackground(new Color(160,3,23));
        lblInicio.setForeground(Color.white);
    }//GEN-LAST:event_lblInicioMouseExited

    private void lblMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuMouseEntered
        panelMenu.setBackground(new Color(108,2,16));
        lblMenu.setForeground(new Color(254,194,169));
    }//GEN-LAST:event_lblMenuMouseEntered

    private void lblMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuMouseExited
        panelMenu.setBackground(new Color(160,3,23));
        lblMenu.setForeground(Color.white);
    }//GEN-LAST:event_lblMenuMouseExited

    private void lblOrdenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOrdenMouseEntered
        panelOrden.setBackground(new Color(108,2,16));
        lblOrden.setForeground(new Color(254,194,169));
    }//GEN-LAST:event_lblOrdenMouseEntered

    private void lblOrdenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOrdenMouseExited
        panelOrden.setBackground(new Color(160,3,23));
        lblOrden.setForeground(Color.white);
    }//GEN-LAST:event_lblOrdenMouseExited

    private void lblListaDeOrdenesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblListaDeOrdenesMouseEntered
        panelListaDeOrdenes.setBackground(new Color(108,2,16));
        lblListaDeOrdenes.setForeground(new Color(254,194,169));
    }//GEN-LAST:event_lblListaDeOrdenesMouseEntered

    private void lblListaDeOrdenesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblListaDeOrdenesMouseExited
        panelListaDeOrdenes.setBackground(new Color(160,3,23));
        lblListaDeOrdenes.setForeground(Color.white);
    }//GEN-LAST:event_lblListaDeOrdenesMouseExited

    private void lblIniciarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIniciarSesionMouseEntered
        panelIniciarSesion.setBackground(new Color(108,2,16));
        lblIniciarSesion.setForeground(new Color(254,194,169));
    }//GEN-LAST:event_lblIniciarSesionMouseEntered

    private void lblIniciarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIniciarSesionMouseExited
        panelIniciarSesion.setBackground(new Color(160,3,23));
        lblIniciarSesion.setForeground(Color.white);
    }//GEN-LAST:event_lblIniciarSesionMouseExited

    private void lblImagenPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagenPedidoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImagenPedidoMouseClicked

    private void mayonesaAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mayonesaAddMouseClicked
            agregarSalsa("Mayonesa");
        try {
            int cantidad = Integer.parseInt(infoMayonesa.getText()) + 1;
            infoMayonesa.setText(String.valueOf(cantidad));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error al leer la cantidad de mayonesa.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_mayonesaAddMouseClicked

    private void ketchupAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ketchupAddMouseClicked
            agregarSalsa("Ketchup");
    try {
        int cantidad = Integer.parseInt(infoKetchup.getText()) + 1;
        infoKetchup.setText(String.valueOf(cantidad));
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Error al leer la cantidad de ketchup.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_ketchupAddMouseClicked

    private void ajiAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajiAddMouseClicked
    agregarSalsa("Ají");
    try {
        int cantidad = Integer.parseInt(infoAji.getText()) + 1;
        infoAji.setText(String.valueOf(cantidad));
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Error al leer la cantidad de ají.", "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_ajiAddMouseClicked

    private void golfAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_golfAddMouseClicked
    agregarSalsa("Golf");
    try {
        int cantidad = Integer.parseInt(infoGolf.getText()) + 1;
        infoGolf.setText(String.valueOf(cantidad));
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Error al leer la cantidad de salsa golf.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_golfAddMouseClicked

    private void mostazaAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostazaAddMouseClicked
    agregarSalsa("Mostaza");
    try {
        int cantidad = Integer.parseInt(infoMostaza.getText()) + 1;
        infoMostaza.setText(String.valueOf(cantidad));
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Error al leer la cantidad de mostaza.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_mostazaAddMouseClicked

    private void tartaraAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tartaraAddMouseClicked
    agregarSalsa("Tártara");
    try {
        int cantidad = Integer.parseInt(infoTartara.getText()) + 1;
        infoTartara.setText(String.valueOf(cantidad));
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Error al leer la cantidad de tártara.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_tartaraAddMouseClicked

    private void bbqAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbqAddMouseClicked
    agregarSalsa("BBQ");
    try {
        int cantidad = Integer.parseInt(infoBBQ.getText()) + 1;
        infoBBQ.setText(String.valueOf(cantidad));
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Error al leer la cantidad de BBQ.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_bbqAddMouseClicked

    private void chimichurriAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chimichurriAddMouseClicked
    agregarSalsa("Chimichurri");
    try {
        int cantidad = Integer.parseInt(infoChimi.getText()) + 1;
        infoChimi.setText(String.valueOf(cantidad));
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Error al leer la cantidad de chimichurri.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_chimichurriAddMouseClicked

    private void labelAgregarOtra1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAgregarOtra1MouseClicked
    Pedido pedido = ControladorPedido.getPedidoActual();

    if (detallePedidoActual != null) {
        pedido.agregarDetalle(detallePedidoActual);
    }

    ControladorPedido.guardarPedido();

    Menu menu = new Menu();
    menu.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_labelAgregarOtra1MouseClicked

    private void verTicketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verTicketMouseClicked
    // Verificar si el pedido tiene detalles antes de mostrar el ticket
    Pedido pedidoActual = ControladorPedido.getPedidoActual();
    pedidoActual.agregarDetalle(detallePedidoActual);
    ControladorPedido.guardarPedido();

    if (pedidoActual != null && pedidoActual.getDetalles().size() > 0) {
        VerTicket vistaTicket = new VerTicket(pedidoActual);
        vistaTicket.setVisible(true);
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "No hay detalles de pedido para mostrar.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_verTicketMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new AgregadoDeCremas().setVisible(true);
            }
        });
    }
       
    private void agregarSalsa(String salsa) {
        if (detallePedidoActual != null) {
            detallePedidoActual.agregarSalsa(salsa);
            salsasAgregadas++;
            if (salsasAgregadas > 8) {
                double nuevoPrecio = detallePedidoActual.getProducto().getPrecio() + COSTO_SALSA_EXTRA;
                detallePedidoActual.getProducto().setPrecio(nuevoPrecio);
                jPrecio.setText(String.valueOf(nuevoPrecio));
            }
            actualizarDetalleSalsas();
        }
    }

    private void actualizarDetalleSalsas() {
        if (detallePedidoActual != null) {
            System.out.println("Salsas añadidas: " + detallePedidoActual.getSalsas());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ajiAdd;
    private javax.swing.JPanel barraMovedora;
    private javax.swing.JLabel bbqAdd;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel chimichurriAdd;
    private javax.swing.JLabel golfAdd;
    private javax.swing.JLabel infoAji;
    private javax.swing.JLabel infoBBQ;
    private javax.swing.JLabel infoChimi;
    private javax.swing.JLabel infoGolf;
    private javax.swing.JLabel infoKetchup;
    private javax.swing.JLabel infoMayonesa;
    private javax.swing.JLabel infoMostaza;
    private javax.swing.JLabel infoTartara;
    private javax.swing.JLabel jDescripcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jPrecio;
    private javax.swing.JLabel ketchupAdd;
    private javax.swing.JLabel labelAgregarOtra1;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblImagenPedido;
    private javax.swing.JLabel lblIniciarSesion;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblListaDeOrdenes;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblOrden;
    private javax.swing.JLabel mayonesaAdd;
    private javax.swing.JLabel mostazaAdd;
    private vista.PanelRound panelAgregarOtra;
    private javax.swing.JPanel panelExit;
    private javax.swing.JPanel panelIniciarSesion;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPanel panelListaDeOrdenes;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelOrden;
    private vista.PanelRound panelRound1;
    private vista.PanelRound panelRound10;
    private vista.PanelRound panelRound11;
    private vista.PanelRound panelRound12;
    private vista.PanelRound panelRound13;
    private vista.PanelRound panelRound14;
    private vista.PanelRound panelRound15;
    private vista.PanelRound panelRound16;
    private vista.PanelRound panelRound17;
    private vista.PanelRound panelRound18;
    private vista.PanelRound panelRound19;
    private vista.PanelRound panelRound2;
    private vista.PanelRound panelRound20;
    private vista.PanelRound panelRound3;
    private vista.PanelRound panelRound4;
    private vista.PanelRound panelRound5;
    private vista.PanelRound panelRound6;
    private vista.PanelRound panelRound7;
    private vista.PanelRound panelRound8;
    private vista.PanelRound panelRound9;
    private javax.swing.JLabel tartaraAdd;
    private javax.swing.JLabel verTicket;
    // End of variables declaration//GEN-END:variables
}
