/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Modelo.Producto;
import java.awt.Color;
import javax.swing.Icon;

/**
 *
 * @author Luis Bizarro
 */
public class Alitas extends javax.swing.JFrame {
    String categoria = "Alitas";
    String id="0";
    String nombre;
    double precio;
    int xMouse, yMouse;
    public Alitas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        imgLogoCocos = new javax.swing.JLabel();
        barraMovedora = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();
        panelExit = new javax.swing.JPanel();
        panelInicio = new javax.swing.JPanel();
        lblInicio = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        lblMenu = new javax.swing.JLabel();
        panelOrden = new javax.swing.JPanel();
        lblOrden = new javax.swing.JLabel();
        panelListaDeOrdenes = new javax.swing.JPanel();
        lblListaDeOrdenes = new javax.swing.JLabel();
        panelIniciarSesion = new javax.swing.JPanel();
        lblIniciarSesion = new javax.swing.JLabel();
        panelRound4 = new vista.PanelRound();
        lblAlitaBroaster = new javax.swing.JLabel();
        imgAlitaBroaster = new javax.swing.JLabel();
        pAlitaBroaster = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelRound8 = new vista.PanelRound();
        lblSalchiAlita = new javax.swing.JLabel();
        imgSalchiAlita = new javax.swing.JLabel();
        pSalchiAlita = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(160, 3, 23));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgLogoCocos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/logoCocosBurger.png"))); // NOI18N
        bg.add(imgLogoCocos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        barraMovedora.setBackground(new java.awt.Color(160, 3, 23));
        barraMovedora.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraMovedoraMouseDragged(evt);
            }
        });
        barraMovedora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraMovedoraMousePressed(evt);
            }
        });

        javax.swing.GroupLayout barraMovedoraLayout = new javax.swing.GroupLayout(barraMovedora);
        barraMovedora.setLayout(barraMovedoraLayout);
        barraMovedoraLayout.setHorizontalGroup(
            barraMovedoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        barraMovedoraLayout.setVerticalGroup(
            barraMovedoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        bg.add(barraMovedora, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 30));

        lblExit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setText("x");
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });
        bg.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 40, 40));

        panelExit.setBackground(new java.awt.Color(160, 3, 23));

        javax.swing.GroupLayout panelExitLayout = new javax.swing.GroupLayout(panelExit);
        panelExit.setLayout(panelExitLayout);
        panelExitLayout.setHorizontalGroup(
            panelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        panelExitLayout.setVerticalGroup(
            panelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        bg.add(panelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 40, 40));

        panelInicio.setBackground(new java.awt.Color(160, 3, 23));

        lblInicio.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        lblInicio.setForeground(new java.awt.Color(255, 255, 255));
        lblInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInicio.setText("Inicio");
        lblInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblInicioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelInicioLayout = new javax.swing.GroupLayout(panelInicio);
        panelInicio.setLayout(panelInicioLayout);
        panelInicioLayout.setHorizontalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        panelInicioLayout.setVerticalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        bg.add(panelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 90, 50));

        panelMenu.setBackground(new java.awt.Color(160, 3, 23));

        lblMenu.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        lblMenu.setForeground(new java.awt.Color(255, 255, 255));
        lblMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenu.setText("Menu");
        lblMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMenuMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 100, -1));

        panelOrden.setBackground(new java.awt.Color(160, 3, 23));

        lblOrden.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        lblOrden.setForeground(new java.awt.Color(255, 255, 255));
        lblOrden.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrden.setText("Orden");
        lblOrden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOrdenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblOrdenMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelOrdenLayout = new javax.swing.GroupLayout(panelOrden);
        panelOrden.setLayout(panelOrdenLayout);
        panelOrdenLayout.setHorizontalGroup(
            panelOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblOrden, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        panelOrdenLayout.setVerticalGroup(
            panelOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOrdenLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(panelOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 110, -1));

        panelListaDeOrdenes.setBackground(new java.awt.Color(160, 3, 23));

        lblListaDeOrdenes.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        lblListaDeOrdenes.setForeground(new java.awt.Color(255, 255, 255));
        lblListaDeOrdenes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblListaDeOrdenes.setText("Lista de ordenes");
        lblListaDeOrdenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblListaDeOrdenesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblListaDeOrdenesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelListaDeOrdenesLayout = new javax.swing.GroupLayout(panelListaDeOrdenes);
        panelListaDeOrdenes.setLayout(panelListaDeOrdenesLayout);
        panelListaDeOrdenesLayout.setHorizontalGroup(
            panelListaDeOrdenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblListaDeOrdenes, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        panelListaDeOrdenesLayout.setVerticalGroup(
            panelListaDeOrdenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelListaDeOrdenesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblListaDeOrdenes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(panelListaDeOrdenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 190, -1));

        panelIniciarSesion.setBackground(new java.awt.Color(160, 3, 23));

        lblIniciarSesion.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        lblIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        lblIniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIniciarSesion.setText("Iniciar sesión");
        lblIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIniciarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIniciarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIniciarSesionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelIniciarSesionLayout = new javax.swing.GroupLayout(panelIniciarSesion);
        panelIniciarSesion.setLayout(panelIniciarSesionLayout);
        panelIniciarSesionLayout.setHorizontalGroup(
            panelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        panelIniciarSesionLayout.setVerticalGroup(
            panelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIniciarSesionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(panelIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, 150, -1));

        panelRound4.setBackground(new java.awt.Color(179, 53, 69));
        panelRound4.setRoundBottomLeft(20);
        panelRound4.setRoundBottomRight(20);
        panelRound4.setRoundTopLeft(20);
        panelRound4.setRoundTopRight(20);

        lblAlitaBroaster.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        lblAlitaBroaster.setForeground(new java.awt.Color(255, 255, 255));
        lblAlitaBroaster.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlitaBroaster.setText("Alita Broaster");
        lblAlitaBroaster.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        imgAlitaBroaster.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgAlitaBroaster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/imagenesProductos/Alitas/alita broaster.png"))); // NOI18N
        imgAlitaBroaster.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgAlitaBroaster.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgAlitaBroasterMouseClicked(evt);
            }
        });

        pAlitaBroaster.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        pAlitaBroaster.setForeground(new java.awt.Color(255, 255, 255));
        pAlitaBroaster.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pAlitaBroaster.setText("11");
        pAlitaBroaster.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound4Layout.createSequentialGroup()
                        .addGap(0, 45, Short.MAX_VALUE)
                        .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound4Layout.createSequentialGroup()
                                .addComponent(lblAlitaBroaster, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound4Layout.createSequentialGroup()
                                .addComponent(pAlitaBroaster, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound4Layout.createSequentialGroup()
                        .addComponent(imgAlitaBroaster, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(imgAlitaBroaster)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAlitaBroaster, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pAlitaBroaster)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 230, 220));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ALITAS");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 110, 730, -1));

        panelRound8.setBackground(new java.awt.Color(179, 53, 69));
        panelRound8.setRoundBottomLeft(20);
        panelRound8.setRoundBottomRight(20);
        panelRound8.setRoundTopLeft(20);
        panelRound8.setRoundTopRight(20);

        lblSalchiAlita.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        lblSalchiAlita.setForeground(new java.awt.Color(255, 255, 255));
        lblSalchiAlita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalchiAlita.setText("SalchiAlita");
        lblSalchiAlita.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        imgSalchiAlita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgSalchiAlita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/imagenesProductos/Alitas/Salchialita.png"))); // NOI18N
        imgSalchiAlita.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgSalchiAlita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgSalchiAlitaMouseClicked(evt);
            }
        });

        pSalchiAlita.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        pSalchiAlita.setForeground(new java.awt.Color(255, 255, 255));
        pSalchiAlita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pSalchiAlita.setText("11");
        pSalchiAlita.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelRound8Layout = new javax.swing.GroupLayout(panelRound8);
        panelRound8.setLayout(panelRound8Layout);
        panelRound8Layout.setHorizontalGroup(
            panelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound8Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(imgSalchiAlita, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addGap(37, 37, 37))
            .addGroup(panelRound8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSalchiAlita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pSalchiAlita, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        panelRound8Layout.setVerticalGroup(
            panelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgSalchiAlita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSalchiAlita, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pSalchiAlita)
                .addGap(69, 69, 69))
        );

        bg.add(panelRound8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 210, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barraMovedoraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraMovedoraMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
           
    }//GEN-LAST:event_barraMovedoraMousePressed

    private void barraMovedoraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraMovedoraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_barraMovedoraMouseDragged

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        // TODO add your handling code here:
        panelExit.setBackground(new Color(251,40,67));
        lblExit.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        panelExit.setBackground(new Color(160,3,23));
        lblExit.setForeground(Color.black);
    }//GEN-LAST:event_lblExitMouseExited

    private void lblInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInicioMouseEntered
        panelInicio.setBackground(new Color(108,2,16));
        lblInicio.setForeground(new Color(254,194,169));
    }//GEN-LAST:event_lblInicioMouseEntered

    private void lblInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInicioMouseExited
        panelInicio.setBackground(new Color(160,3,23));
        lblInicio.setForeground(Color.white);
    }//GEN-LAST:event_lblInicioMouseExited

    private void lblMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuMouseEntered
        panelMenu.setBackground(new Color(108,2,16));
        lblMenu.setForeground(new Color(254,194,169));
    }//GEN-LAST:event_lblMenuMouseEntered

    private void lblMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuMouseExited
        panelMenu.setBackground(new Color(160,3,23));
        lblMenu.setForeground(Color.white);
    }//GEN-LAST:event_lblMenuMouseExited

    private void lblOrdenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOrdenMouseEntered
        panelOrden.setBackground(new Color(108,2,16));
        lblOrden.setForeground(new Color(254,194,169));
    }//GEN-LAST:event_lblOrdenMouseEntered

    private void lblOrdenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOrdenMouseExited
        panelOrden.setBackground(new Color(160,3,23));
        lblOrden.setForeground(Color.white);
    }//GEN-LAST:event_lblOrdenMouseExited

    private void lblListaDeOrdenesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblListaDeOrdenesMouseEntered
        panelListaDeOrdenes.setBackground(new Color(108,2,16));
        lblListaDeOrdenes.setForeground(new Color(254,194,169));
    }//GEN-LAST:event_lblListaDeOrdenesMouseEntered

    private void lblListaDeOrdenesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblListaDeOrdenesMouseExited
        panelListaDeOrdenes.setBackground(new Color(160,3,23));
        lblListaDeOrdenes.setForeground(Color.white);
    }//GEN-LAST:event_lblListaDeOrdenesMouseExited

    private void lblIniciarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIniciarSesionMouseEntered
        panelIniciarSesion.setBackground(new Color(108,2,16));
        lblIniciarSesion.setForeground(new Color(254,194,169));
    }//GEN-LAST:event_lblIniciarSesionMouseEntered

    private void lblIniciarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIniciarSesionMouseExited
        panelIniciarSesion.setBackground(new Color(160,3,23));
        lblIniciarSesion.setForeground(Color.white);
    }//GEN-LAST:event_lblIniciarSesionMouseExited

    private void lblInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInicioMouseClicked
        Inicio objetoInicio = new Inicio();
        objetoInicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblInicioMouseClicked

    private void lblMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuMouseClicked
        Menu objetoMenu = new Menu();
        objetoMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblMenuMouseClicked

    private void lblIniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIniciarSesionMouseClicked
        LoginV objetoLogin = new LoginV();
        objetoLogin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblIniciarSesionMouseClicked

    private void imgSalchiAlitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgSalchiAlitaMouseClicked
        // TODO add your handling code here:
        id="1";
        nombre = lblSalchiAlita.getText();
        precio = Double.parseDouble(pSalchiAlita.getText());
        Producto salchiAlita = new Producto(id, nombre, precio, categoria);
        Icon iconoSalchiAlita = imgSalchiAlita.getIcon();

        
        AgregadoDeCremas ventanaCremas = new AgregadoDeCremas(salchiAlita, iconoSalchiAlita);
        ventanaCremas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_imgSalchiAlitaMouseClicked

    private void imgAlitaBroasterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgAlitaBroasterMouseClicked
        // TODO add your handling code here:
        id="2";
        nombre = lblAlitaBroaster.getText();
        precio = Double.parseDouble(pAlitaBroaster.getText());
        Producto alitaBroaster = new Producto(id, nombre, precio, categoria);
        Icon iconoAlitaBroaster = imgAlitaBroaster.getIcon();

        
        AgregadoDeCremas ventanaCremas = new AgregadoDeCremas(alitaBroaster, iconoAlitaBroaster);
        ventanaCremas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_imgAlitaBroasterMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Alitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraMovedora;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel imgAlitaBroaster;
    private javax.swing.JLabel imgLogoCocos;
    private javax.swing.JLabel imgSalchiAlita;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAlitaBroaster;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblIniciarSesion;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblListaDeOrdenes;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblOrden;
    private javax.swing.JLabel lblSalchiAlita;
    private javax.swing.JLabel pAlitaBroaster;
    private javax.swing.JLabel pSalchiAlita;
    private javax.swing.JPanel panelExit;
    private javax.swing.JPanel panelIniciarSesion;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPanel panelListaDeOrdenes;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelOrden;
    private vista.PanelRound panelRound4;
    private vista.PanelRound panelRound8;
    // End of variables declaration//GEN-END:variables
}
