/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Modelo.Producto;
import java.awt.Color;
import javax.swing.Icon;

/**
 *
 * @author Luis Bizarro
 */
public class Hamburguesas extends javax.swing.JFrame {

    int xMouse, yMouse;
    String categoria = "Hamburguesas";
    String id="0";
    String nombre;
    double precio;
    public Hamburguesas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        barraMovedora = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();
        panelExit = new javax.swing.JPanel();
        panelInicio = new javax.swing.JPanel();
        lblInicio = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        lblMenu = new javax.swing.JLabel();
        panelOrden = new javax.swing.JPanel();
        lblOrden = new javax.swing.JLabel();
        panelListaDeOrdenes = new javax.swing.JPanel();
        lblListaDeOrdenes = new javax.swing.JLabel();
        panelIniciarSesion = new javax.swing.JPanel();
        lblIniciarSesion = new javax.swing.JLabel();
        panelRound4 = new vista.PanelRound();
        lblHamburguesaDeCasaHawaianaMasPlatano = new javax.swing.JLabel();
        imgHamburguesaCasaHawaianaPlatano = new javax.swing.JLabel();
        pHCasaHawainaPlatano1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelRound5 = new vista.PanelRound();
        lblHamburguesaDeCasa = new javax.swing.JLabel();
        imgHamburguesaDeCasa = new javax.swing.JLabel();
        pHCasa = new javax.swing.JLabel();
        panelRound6 = new vista.PanelRound();
        lblHamburguesaDeCasaPobre = new javax.swing.JLabel();
        imgHamburguesaDeCasaPobre = new javax.swing.JLabel();
        pHCasaP = new javax.swing.JLabel();
        panelRound7 = new vista.PanelRound();
        lblHamburguesaDeCasaHawaiana = new javax.swing.JLabel();
        imgHamburguesaCasaHawaiana = new javax.swing.JLabel();
        pHCasaHawaina1 = new javax.swing.JLabel();
        panelRound8 = new vista.PanelRound();
        imgHamburguesaCasaRoyal = new javax.swing.JLabel();
        lblHamburguesaDeCasaRoyal1 = new javax.swing.JLabel();
        pHCasaRoyal = new javax.swing.JLabel();
        panelRound9 = new vista.PanelRound();
        lblHamburguesaDeCasaTocino = new javax.swing.JLabel();
        imgHamburguesaCasaTocino = new javax.swing.JLabel();
        pHCasaT = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(160, 3, 23));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/logoCocosBurger.png"))); // NOI18N
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        barraMovedora.setBackground(new java.awt.Color(160, 3, 23));
        barraMovedora.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraMovedoraMouseDragged(evt);
            }
        });
        barraMovedora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraMovedoraMousePressed(evt);
            }
        });

        javax.swing.GroupLayout barraMovedoraLayout = new javax.swing.GroupLayout(barraMovedora);
        barraMovedora.setLayout(barraMovedoraLayout);
        barraMovedoraLayout.setHorizontalGroup(
            barraMovedoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        barraMovedoraLayout.setVerticalGroup(
            barraMovedoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        bg.add(barraMovedora, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 30));

        lblExit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setText("x");
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });
        bg.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 40, 40));

        panelExit.setBackground(new java.awt.Color(160, 3, 23));

        javax.swing.GroupLayout panelExitLayout = new javax.swing.GroupLayout(panelExit);
        panelExit.setLayout(panelExitLayout);
        panelExitLayout.setHorizontalGroup(
            panelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        panelExitLayout.setVerticalGroup(
            panelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        bg.add(panelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 40, 40));

        panelInicio.setBackground(new java.awt.Color(160, 3, 23));

        lblInicio.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        lblInicio.setForeground(new java.awt.Color(255, 255, 255));
        lblInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInicio.setText("Inicio");
        lblInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblInicioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelInicioLayout = new javax.swing.GroupLayout(panelInicio);
        panelInicio.setLayout(panelInicioLayout);
        panelInicioLayout.setHorizontalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        panelInicioLayout.setVerticalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        bg.add(panelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 90, 50));

        panelMenu.setBackground(new java.awt.Color(160, 3, 23));

        lblMenu.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        lblMenu.setForeground(new java.awt.Color(255, 255, 255));
        lblMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenu.setText("Menu");
        lblMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMenuMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 100, -1));

        panelOrden.setBackground(new java.awt.Color(160, 3, 23));

        lblOrden.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        lblOrden.setForeground(new java.awt.Color(255, 255, 255));
        lblOrden.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrden.setText("Orden");
        lblOrden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOrdenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblOrdenMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelOrdenLayout = new javax.swing.GroupLayout(panelOrden);
        panelOrden.setLayout(panelOrdenLayout);
        panelOrdenLayout.setHorizontalGroup(
            panelOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblOrden, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        panelOrdenLayout.setVerticalGroup(
            panelOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOrdenLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(panelOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 110, -1));

        panelListaDeOrdenes.setBackground(new java.awt.Color(160, 3, 23));

        lblListaDeOrdenes.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        lblListaDeOrdenes.setForeground(new java.awt.Color(255, 255, 255));
        lblListaDeOrdenes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblListaDeOrdenes.setText("Lista de ordenes");
        lblListaDeOrdenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblListaDeOrdenesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblListaDeOrdenesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelListaDeOrdenesLayout = new javax.swing.GroupLayout(panelListaDeOrdenes);
        panelListaDeOrdenes.setLayout(panelListaDeOrdenesLayout);
        panelListaDeOrdenesLayout.setHorizontalGroup(
            panelListaDeOrdenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblListaDeOrdenes, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        panelListaDeOrdenesLayout.setVerticalGroup(
            panelListaDeOrdenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelListaDeOrdenesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblListaDeOrdenes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(panelListaDeOrdenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 190, -1));

        panelIniciarSesion.setBackground(new java.awt.Color(160, 3, 23));

        lblIniciarSesion.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        lblIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        lblIniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIniciarSesion.setText("Iniciar sesión");
        lblIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIniciarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIniciarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIniciarSesionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelIniciarSesionLayout = new javax.swing.GroupLayout(panelIniciarSesion);
        panelIniciarSesion.setLayout(panelIniciarSesionLayout);
        panelIniciarSesionLayout.setHorizontalGroup(
            panelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        panelIniciarSesionLayout.setVerticalGroup(
            panelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIniciarSesionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(panelIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, 150, -1));

        panelRound4.setBackground(new java.awt.Color(179, 53, 69));
        panelRound4.setRoundBottomLeft(20);
        panelRound4.setRoundBottomRight(20);
        panelRound4.setRoundTopLeft(20);
        panelRound4.setRoundTopRight(20);

        lblHamburguesaDeCasaHawaianaMasPlatano.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        lblHamburguesaDeCasaHawaianaMasPlatano.setForeground(new java.awt.Color(255, 255, 255));
        lblHamburguesaDeCasaHawaianaMasPlatano.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHamburguesaDeCasaHawaianaMasPlatano.setText("Hamburguesa de casa Hawaina + platano");
        lblHamburguesaDeCasaHawaianaMasPlatano.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        imgHamburguesaCasaHawaianaPlatano.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgHamburguesaCasaHawaianaPlatano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/imagenesProductos/Hamburguesas/hamburguesaHawaianaPlatano.png"))); // NOI18N
        imgHamburguesaCasaHawaianaPlatano.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgHamburguesaCasaHawaianaPlatano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgHamburguesaCasaHawaianaPlatanoMouseClicked(evt);
            }
        });

        pHCasaHawainaPlatano1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        pHCasaHawainaPlatano1.setForeground(new java.awt.Color(255, 255, 255));
        pHCasaHawainaPlatano1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pHCasaHawainaPlatano1.setText("11.5");
        pHCasaHawainaPlatano1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addComponent(lblHamburguesaDeCasaHawaianaMasPlatano, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgHamburguesaCasaHawaianaPlatano, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRound4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pHCasaHawainaPlatano1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgHamburguesaCasaHawaianaPlatano)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHamburguesaDeCasaHawaianaMasPlatano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(48, 48, 48))
            .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound4Layout.createSequentialGroup()
                    .addContainerGap(184, Short.MAX_VALUE)
                    .addComponent(pHCasaHawainaPlatano1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(3, 3, 3)))
        );

        bg.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 230, 210));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("HAMBURGUESAS");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 110, 730, -1));

        panelRound5.setBackground(new java.awt.Color(179, 53, 69));
        panelRound5.setRoundBottomLeft(20);
        panelRound5.setRoundBottomRight(20);
        panelRound5.setRoundTopLeft(20);
        panelRound5.setRoundTopRight(20);

        lblHamburguesaDeCasa.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        lblHamburguesaDeCasa.setForeground(new java.awt.Color(255, 255, 255));
        lblHamburguesaDeCasa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHamburguesaDeCasa.setText("Hamburguesa de casa");
        lblHamburguesaDeCasa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        imgHamburguesaDeCasa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgHamburguesaDeCasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/hamburguesaMenu.png"))); // NOI18N
        imgHamburguesaDeCasa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgHamburguesaDeCasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgHamburguesaDeCasaMouseClicked(evt);
            }
        });

        pHCasa.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        pHCasa.setForeground(new java.awt.Color(255, 255, 255));
        pHCasa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pHCasa.setText("9.5");
        pHCasa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelRound5Layout = new javax.swing.GroupLayout(panelRound5);
        panelRound5.setLayout(panelRound5Layout);
        panelRound5Layout.setHorizontalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound5Layout.createSequentialGroup()
                .addGroup(panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound5Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(pHCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblHamburguesaDeCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound5Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(imgHamburguesaDeCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound5Layout.setVerticalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgHamburguesaDeCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHamburguesaDeCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pHCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        bg.add(panelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 210, 200));

        panelRound6.setBackground(new java.awt.Color(179, 53, 69));
        panelRound6.setRoundBottomLeft(20);
        panelRound6.setRoundBottomRight(20);
        panelRound6.setRoundTopLeft(20);
        panelRound6.setRoundTopRight(20);

        lblHamburguesaDeCasaPobre.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        lblHamburguesaDeCasaPobre.setForeground(new java.awt.Color(255, 255, 255));
        lblHamburguesaDeCasaPobre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHamburguesaDeCasaPobre.setText("Hamburguesa De Casa Pobre");
        lblHamburguesaDeCasaPobre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        imgHamburguesaDeCasaPobre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgHamburguesaDeCasaPobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/imagenesProductos/Hamburguesas/hamburguesaPobre.png"))); // NOI18N
        imgHamburguesaDeCasaPobre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgHamburguesaDeCasaPobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgHamburguesaDeCasaPobreMouseClicked(evt);
            }
        });

        pHCasaP.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        pHCasaP.setForeground(new java.awt.Color(255, 255, 255));
        pHCasaP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pHCasaP.setText("11");
        pHCasaP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelRound6Layout = new javax.swing.GroupLayout(panelRound6);
        panelRound6.setLayout(panelRound6Layout);
        panelRound6Layout.setHorizontalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound6Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(pHCasaP, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelRound6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHamburguesaDeCasaPobre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(75, 75, 75))
            .addGroup(panelRound6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(imgHamburguesaDeCasaPobre, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound6Layout.setVerticalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgHamburguesaDeCasaPobre, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHamburguesaDeCasaPobre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pHCasaP, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bg.add(panelRound6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 190, 190));

        panelRound7.setBackground(new java.awt.Color(179, 53, 69));
        panelRound7.setRoundBottomLeft(20);
        panelRound7.setRoundBottomRight(20);
        panelRound7.setRoundTopLeft(20);
        panelRound7.setRoundTopRight(20);

        lblHamburguesaDeCasaHawaiana.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        lblHamburguesaDeCasaHawaiana.setForeground(new java.awt.Color(255, 255, 255));
        lblHamburguesaDeCasaHawaiana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHamburguesaDeCasaHawaiana.setText("Hamburguesa de casa Hawaina");
        lblHamburguesaDeCasaHawaiana.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        imgHamburguesaCasaHawaiana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgHamburguesaCasaHawaiana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/imagenesProductos/Hamburguesas/hamburguesaHawaiana.png"))); // NOI18N
        imgHamburguesaCasaHawaiana.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgHamburguesaCasaHawaiana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgHamburguesaCasaHawaianaMouseClicked(evt);
            }
        });

        pHCasaHawaina1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        pHCasaHawaina1.setForeground(new java.awt.Color(255, 255, 255));
        pHCasaHawaina1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pHCasaHawaina1.setText("11");
        pHCasaHawaina1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelRound7Layout = new javax.swing.GroupLayout(panelRound7);
        panelRound7.setLayout(panelRound7Layout);
        panelRound7Layout.setHorizontalGroup(
            panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(imgHamburguesaCasaHawaiana, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblHamburguesaDeCasaHawaiana))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound7Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(pHCasaHawaina1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelRound7Layout.setVerticalGroup(
            panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgHamburguesaCasaHawaiana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHamburguesaDeCasaHawaiana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(54, 54, 54))
            .addGroup(panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound7Layout.createSequentialGroup()
                    .addContainerGap(184, Short.MAX_VALUE)
                    .addComponent(pHCasaHawaina1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(9, 9, 9)))
        );

        bg.add(panelRound7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 210, 210));

        panelRound8.setBackground(new java.awt.Color(179, 53, 69));
        panelRound8.setRoundBottomLeft(20);
        panelRound8.setRoundBottomRight(20);
        panelRound8.setRoundTopLeft(20);
        panelRound8.setRoundTopRight(20);

        imgHamburguesaCasaRoyal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgHamburguesaCasaRoyal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/imagenesProductos/Hamburguesas/hamburguesaDeCasaRoyal.png"))); // NOI18N
        imgHamburguesaCasaRoyal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgHamburguesaCasaRoyal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgHamburguesaCasaRoyalMouseClicked(evt);
            }
        });

        lblHamburguesaDeCasaRoyal1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        lblHamburguesaDeCasaRoyal1.setForeground(new java.awt.Color(255, 255, 255));
        lblHamburguesaDeCasaRoyal1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHamburguesaDeCasaRoyal1.setText("Hamburguesa de casa Royal");
        lblHamburguesaDeCasaRoyal1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pHCasaRoyal.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        pHCasaRoyal.setForeground(new java.awt.Color(255, 255, 255));
        pHCasaRoyal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pHCasaRoyal.setText("11");
        pHCasaRoyal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelRound8Layout = new javax.swing.GroupLayout(panelRound8);
        panelRound8.setLayout(panelRound8Layout);
        panelRound8Layout.setHorizontalGroup(
            panelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgHamburguesaCasaRoyal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHamburguesaDeCasaRoyal1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(panelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRound8Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pHCasaRoyal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelRound8Layout.setVerticalGroup(
            panelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound8Layout.createSequentialGroup()
                .addComponent(imgHamburguesaCasaRoyal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHamburguesaDeCasaRoyal1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(panelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound8Layout.createSequentialGroup()
                    .addContainerGap(167, Short.MAX_VALUE)
                    .addComponent(pHCasaRoyal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)))
        );

        bg.add(panelRound8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 210, 200));

        panelRound9.setBackground(new java.awt.Color(179, 53, 69));
        panelRound9.setRoundBottomLeft(20);
        panelRound9.setRoundBottomRight(20);
        panelRound9.setRoundTopLeft(20);
        panelRound9.setRoundTopRight(20);

        lblHamburguesaDeCasaTocino.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        lblHamburguesaDeCasaTocino.setForeground(new java.awt.Color(255, 255, 255));
        lblHamburguesaDeCasaTocino.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHamburguesaDeCasaTocino.setText("Hamburguesa De Casa Tocino");
        lblHamburguesaDeCasaTocino.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        imgHamburguesaCasaTocino.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgHamburguesaCasaTocino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/imagenesProductos/Hamburguesas/hamburguesaCasaMasTocino.png"))); // NOI18N
        imgHamburguesaCasaTocino.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgHamburguesaCasaTocino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgHamburguesaCasaTocinoMouseClicked(evt);
            }
        });

        pHCasaT.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        pHCasaT.setForeground(new java.awt.Color(255, 255, 255));
        pHCasaT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pHCasaT.setText("11");
        pHCasaT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelRound9Layout = new javax.swing.GroupLayout(panelRound9);
        panelRound9.setLayout(panelRound9Layout);
        panelRound9Layout.setHorizontalGroup(
            panelRound9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHamburguesaDeCasaTocino, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addGroup(panelRound9Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(imgHamburguesaCasaTocino, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pHCasaT, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        panelRound9Layout.setVerticalGroup(
            panelRound9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound9Layout.createSequentialGroup()
                .addComponent(imgHamburguesaCasaTocino, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHamburguesaDeCasaTocino, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pHCasaT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bg.add(panelRound9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 230, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barraMovedoraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraMovedoraMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
           
    }//GEN-LAST:event_barraMovedoraMousePressed

    private void barraMovedoraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraMovedoraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_barraMovedoraMouseDragged

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        // TODO add your handling code here:
        panelExit.setBackground(new Color(251,40,67));
        lblExit.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        panelExit.setBackground(new Color(160,3,23));
        lblExit.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lblExitMouseExited

    private void lblInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInicioMouseEntered
        panelInicio.setBackground(new Color(108,2,16));
        lblInicio.setForeground(new Color(254,194,169));
    }//GEN-LAST:event_lblInicioMouseEntered

    private void lblInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInicioMouseExited
        panelInicio.setBackground(new Color(160,3,23));
        lblInicio.setForeground(Color.white);
    }//GEN-LAST:event_lblInicioMouseExited

    private void lblMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuMouseEntered
        panelMenu.setBackground(new Color(108,2,16));
        lblMenu.setForeground(new Color(254,194,169));
    }//GEN-LAST:event_lblMenuMouseEntered

    private void lblMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuMouseExited
        panelMenu.setBackground(new Color(160,3,23));
        lblMenu.setForeground(Color.white);
    }//GEN-LAST:event_lblMenuMouseExited

    private void lblOrdenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOrdenMouseEntered
        panelOrden.setBackground(new Color(108,2,16));
        lblOrden.setForeground(new Color(254,194,169));
    }//GEN-LAST:event_lblOrdenMouseEntered

    private void lblOrdenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOrdenMouseExited
        panelOrden.setBackground(new Color(160,3,23));
        lblOrden.setForeground(Color.white);
    }//GEN-LAST:event_lblOrdenMouseExited

    private void lblListaDeOrdenesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblListaDeOrdenesMouseEntered
        panelListaDeOrdenes.setBackground(new Color(108,2,16));
        lblListaDeOrdenes.setForeground(new Color(254,194,169));
    }//GEN-LAST:event_lblListaDeOrdenesMouseEntered

    private void lblListaDeOrdenesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblListaDeOrdenesMouseExited
        panelListaDeOrdenes.setBackground(new Color(160,3,23));
        lblListaDeOrdenes.setForeground(Color.white);
    }//GEN-LAST:event_lblListaDeOrdenesMouseExited

    private void lblIniciarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIniciarSesionMouseEntered
        panelIniciarSesion.setBackground(new Color(108,2,16));
        lblIniciarSesion.setForeground(new Color(254,194,169));
    }//GEN-LAST:event_lblIniciarSesionMouseEntered

    private void lblIniciarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIniciarSesionMouseExited
        panelIniciarSesion.setBackground(new Color(160,3,23));
        lblIniciarSesion.setForeground(Color.white);
    }//GEN-LAST:event_lblIniciarSesionMouseExited

    private void lblInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInicioMouseClicked
        Inicio objetoInicio = new Inicio();
        objetoInicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblInicioMouseClicked

    private void lblMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuMouseClicked
        Menu objetoMenu = new Menu();
        objetoMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblMenuMouseClicked

    private void lblIniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIniciarSesionMouseClicked
        LoginV objetoLogin = new LoginV();
        objetoLogin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblIniciarSesionMouseClicked

    private void imgHamburguesaCasaRoyalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgHamburguesaCasaRoyalMouseClicked
        // TODO add your handling code here:
        id="7";
        nombre = lblHamburguesaDeCasaRoyal1.getText();
        precio = Double.parseDouble(pHCasaRoyal.getText());
        Producto hCasaRoyal = new Producto(id, nombre, precio, categoria);
        Icon iconoHCasaRoyal = imgHamburguesaCasaRoyal.getIcon();

        AgregadoDeCremas ventanaCremas = new AgregadoDeCremas(hCasaRoyal, iconoHCasaRoyal);
        ventanaCremas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_imgHamburguesaCasaRoyalMouseClicked

    private void imgHamburguesaCasaHawaianaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgHamburguesaCasaHawaianaMouseClicked
        // TODO add your handling code here:
        id="8";
        nombre = lblHamburguesaDeCasaHawaiana.getText();
        precio = Double.parseDouble(pHCasaHawaina1.getText());
        Producto hCasaH = new Producto(id, nombre, precio, categoria);
        Icon iconoHCasaH = imgHamburguesaCasaHawaiana.getIcon();

        AgregadoDeCremas ventanaCremas = new AgregadoDeCremas(hCasaH, iconoHCasaH);
        ventanaCremas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_imgHamburguesaCasaHawaianaMouseClicked

    private void imgHamburguesaCasaHawaianaPlatanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgHamburguesaCasaHawaianaPlatanoMouseClicked
        // TODO add your handling code here:
        id="9";
        nombre = lblHamburguesaDeCasaHawaianaMasPlatano.getText();
        precio = Double.parseDouble(pHCasaHawainaPlatano1.getText());
        Producto hCasaHP = new Producto(id, nombre, precio, categoria);
        Icon iconoHCasaHP = imgHamburguesaCasaHawaianaPlatano.getIcon();

        AgregadoDeCremas ventanaCremas = new AgregadoDeCremas(hCasaHP, iconoHCasaHP);
        ventanaCremas.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_imgHamburguesaCasaHawaianaPlatanoMouseClicked

    private void imgHamburguesaDeCasaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgHamburguesaDeCasaMouseClicked
        // TODO add your handling code here:
         id="10";
        nombre = lblHamburguesaDeCasa.getText();
        precio = Double.parseDouble(pHCasa.getText());
        Producto hCasa = new Producto(id, nombre, precio, categoria);
        Icon iconoHCasa = imgHamburguesaDeCasa.getIcon();

        AgregadoDeCremas ventanaCremas = new AgregadoDeCremas(hCasa, iconoHCasa);
        ventanaCremas.setVisible(true);
        this.dispose();    
    }//GEN-LAST:event_imgHamburguesaDeCasaMouseClicked

    private void imgHamburguesaDeCasaPobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgHamburguesaDeCasaPobreMouseClicked
        // TODO add your handling code here:
        id="11";
        nombre = lblHamburguesaDeCasaPobre.getText();
        precio = Double.parseDouble(pHCasaP.getText());
        Producto hCasaP = new Producto(id, nombre, precio, categoria);
        Icon iconoHCasaP = imgHamburguesaDeCasaPobre.getIcon();

        AgregadoDeCremas ventanaCremas = new AgregadoDeCremas(hCasaP, iconoHCasaP);
        ventanaCremas.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_imgHamburguesaDeCasaPobreMouseClicked

    private void imgHamburguesaCasaTocinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgHamburguesaCasaTocinoMouseClicked
        // TODO add your handling code here:
        id="12";
        nombre = lblHamburguesaDeCasaTocino.getText();
        precio = Double.parseDouble(pHCasaT.getText());
        Producto hCasaT = new Producto(id, nombre, precio, categoria);
        Icon iconoHCasaT = imgHamburguesaCasaTocino.getIcon();

        AgregadoDeCremas ventanaCremas = new AgregadoDeCremas(hCasaT, iconoHCasaT);
        ventanaCremas.setVisible(true);
        this.dispose();         
    }//GEN-LAST:event_imgHamburguesaCasaTocinoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Hamburguesas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraMovedora;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel imgHamburguesaCasaHawaiana;
    private javax.swing.JLabel imgHamburguesaCasaHawaianaPlatano;
    private javax.swing.JLabel imgHamburguesaCasaRoyal;
    private javax.swing.JLabel imgHamburguesaCasaTocino;
    private javax.swing.JLabel imgHamburguesaDeCasa;
    private javax.swing.JLabel imgHamburguesaDeCasaPobre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblHamburguesaDeCasa;
    private javax.swing.JLabel lblHamburguesaDeCasaHawaiana;
    private javax.swing.JLabel lblHamburguesaDeCasaHawaianaMasPlatano;
    private javax.swing.JLabel lblHamburguesaDeCasaPobre;
    private javax.swing.JLabel lblHamburguesaDeCasaRoyal1;
    private javax.swing.JLabel lblHamburguesaDeCasaTocino;
    private javax.swing.JLabel lblIniciarSesion;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblListaDeOrdenes;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblOrden;
    private javax.swing.JLabel pHCasa;
    private javax.swing.JLabel pHCasaHawaina1;
    private javax.swing.JLabel pHCasaHawainaPlatano1;
    private javax.swing.JLabel pHCasaP;
    private javax.swing.JLabel pHCasaRoyal;
    private javax.swing.JLabel pHCasaT;
    private javax.swing.JPanel panelExit;
    private javax.swing.JPanel panelIniciarSesion;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPanel panelListaDeOrdenes;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelOrden;
    private vista.PanelRound panelRound4;
    private vista.PanelRound panelRound5;
    private vista.PanelRound panelRound6;
    private vista.PanelRound panelRound7;
    private vista.PanelRound panelRound8;
    private vista.PanelRound panelRound9;
    // End of variables declaration//GEN-END:variables
}
