/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Archivo.Archivo;
import javax.swing.JFrame;

/**
 *
 * @author Usuario
 */
public class MenuCategorias extends javax.swing.JFrame {
    private static final String NOMBRE_ARCHIVO = "DatosProductos.txt";
    /**
     * Creates new form MenuCategorias
     */
    public MenuCategorias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bHamburguesas = new javax.swing.JButton();
        bSalchipapas = new javax.swing.JButton();
        bAlitas = new javax.swing.JButton();
        bCombos = new javax.swing.JButton();
        bBebidas = new javax.swing.JButton();
        bBroasters = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bHamburguesas.setText(" Hamburguesas");
        bHamburguesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHamburguesasActionPerformed(evt);
            }
        });

        bSalchipapas.setText("Salchipapas");
        bSalchipapas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalchipapasActionPerformed(evt);
            }
        });

        bAlitas.setText("Alitas");
        bAlitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAlitasActionPerformed(evt);
            }
        });

        bCombos.setText("Combos");
        bCombos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCombosActionPerformed(evt);
            }
        });

        bBebidas.setText("Bebidas");
        bBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBebidasActionPerformed(evt);
            }
        });

        bBroasters.setBackground(new java.awt.Color(204, 204, 204));
        bBroasters.setText("Broasters");
        bBroasters.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bBroasters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBroastersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(bBroasters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(bHamburguesas))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(bSalchipapas)
                        .addGap(47, 47, 47)
                        .addComponent(bCombos)
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bAlitas)
                    .addComponent(bBebidas))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bBroasters, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bAlitas)
                        .addComponent(bHamburguesas)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSalchipapas)
                    .addComponent(bCombos)
                    .addComponent(bBebidas))
                .addGap(117, 117, 117))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bHamburguesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHamburguesasActionPerformed
        // TODO add your handling code here:
        Archivo archivo = new Archivo("DatosProductos.txt");
    
        // Crear la ventana de productos y mostrarla
        JFrame ventana = new JFrame("Productos - Hamburguesas");
        ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ventana.add(new VentanaProductos("hamburguesas", archivo)); // Pasa la categoría y el objeto Archivo
        ventana.setSize(400, 400);
        ventana.setVisible(true);
    }//GEN-LAST:event_bHamburguesasActionPerformed

    private void bBroastersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBroastersActionPerformed
    Archivo archivo = new Archivo("DatosProductos.txt");
    
    // Crear la ventana de productos y mostrarla
    JFrame ventana = new JFrame("Productos - Broasters");
    ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    ventana.add(new VentanaProductos("Broasters", archivo)); // Pasa la categoría y el objeto Archivo
    ventana.setSize(400, 400);
    ventana.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_bBroastersActionPerformed

    private void bSalchipapasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalchipapasActionPerformed
        // TODO add your handling code here:
    Archivo archivo = new Archivo("DatosProductos.txt");
    
    // Crear la ventana de productos y mostrarla
    JFrame ventana = new JFrame("Productos - Salchipapas");
    ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    ventana.add(new VentanaProductos("Salchipapas", archivo)); // Pasa la categoría y el objeto Archivo
    ventana.setSize(400, 400);
    ventana.setVisible(true);

    }//GEN-LAST:event_bSalchipapasActionPerformed

    private void bAlitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAlitasActionPerformed
        // TODO add your handling code here:
         Archivo archivo = new Archivo("DatosProductos.txt");
    
    // Crear la ventana de productos y mostrarla
    JFrame ventana = new JFrame("Productos - Alitas");
    ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    ventana.add(new VentanaProductos("Alitas", archivo)); // Pasa la categoría y el objeto Archivo
    ventana.setSize(400, 400);
    ventana.setVisible(true);   
    }//GEN-LAST:event_bAlitasActionPerformed

    private void bCombosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCombosActionPerformed
        // TODO add your handling code here:
        Archivo archivo = new Archivo("DatosProductos.txt");
    
    // Crear la ventana de productos y mostrarla
    JFrame ventana = new JFrame("Productos - Combos");
    ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    ventana.add(new VentanaProductos("Combos", archivo)); // Pasa la categoría y el objeto Archivo
    ventana.setSize(400, 400);
    ventana.setVisible(true);
    }//GEN-LAST:event_bCombosActionPerformed

    private void bBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBebidasActionPerformed
        // TODO add your handling code here:
          Archivo archivo = new Archivo("DatosProductos.txt");
    
    // Crear la ventana de productos y mostrarla
        JFrame ventana = new JFrame("Productos - Bebidas");
        ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ventana.add(new VentanaProductos("Bebidas", archivo)); // Pasa la categoría y el objeto Archivo
        ventana.setSize(400, 400);
        ventana.setVisible(true);
    }//GEN-LAST:event_bBebidasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCategorias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAlitas;
    private javax.swing.JButton bBebidas;
    private javax.swing.JButton bBroasters;
    private javax.swing.JButton bCombos;
    private javax.swing.JButton bHamburguesas;
    private javax.swing.JButton bSalchipapas;
    // End of variables declaration//GEN-END:variables
}
