/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import Modelo.ArchivoPersonal;
import Modelo.Cajero;
import Modelo.Personal;

/**
 *
 * @author Luis Bizarro
 */
public class RegistroCajeros extends javax.swing.JFrame {

    int xMouse, yMouse;
    public RegistroCajeros() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        panelRound1 = new vista.PanelRound();
        lblIngreseSuApellido = new javax.swing.JLabel();
        panelUsuario = new vista.PanelRound();
        txtFieldNombreUsuario = new javax.swing.JTextField();
        panelIngresar = new vista.PanelRound();
        lblRegistrarse = new javax.swing.JLabel();
        panelApellido = new vista.PanelRound();
        txtFieldApellido = new javax.swing.JTextField();
        lblIngreseSuNombre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        imgHamburguesa = new javax.swing.JLabel();
        barraMovedora = new javax.swing.JPanel();
        panelExit = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();
        lblCocosBurguer = new javax.swing.JLabel();
        imgHamburguesa1 = new javax.swing.JLabel();
        panelRegresar = new vista.PanelRound();
        lblRegresar = new javax.swing.JLabel();
        lblRegistrarse1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(160, 3, 23));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(179, 53, 69));
        panelRound1.setRoundBottomLeft(25);
        panelRound1.setRoundBottomRight(25);
        panelRound1.setRoundTopLeft(25);
        panelRound1.setRoundTopRight(25);

        lblIngreseSuApellido.setFont(new java.awt.Font("Burbank Big Cd Bd", 0, 30)); // NOI18N
        lblIngreseSuApellido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIngreseSuApellido.setText("INGRESE SU APELLIDO:");

        panelUsuario.setBackground(new java.awt.Color(216, 152, 160));
        panelUsuario.setRoundBottomLeft(20);
        panelUsuario.setRoundBottomRight(20);
        panelUsuario.setRoundTopLeft(20);
        panelUsuario.setRoundTopRight(20);

        txtFieldNombreUsuario.setBackground(new java.awt.Color(216, 152, 160));
        txtFieldNombreUsuario.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        txtFieldNombreUsuario.setForeground(new java.awt.Color(204, 204, 204));
        txtFieldNombreUsuario.setText("Ingrese su nombre");
        txtFieldNombreUsuario.setBorder(null);
        txtFieldNombreUsuario.setSelectedTextColor(new java.awt.Color(204, 204, 255));
        txtFieldNombreUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFieldNombreUsuarioMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtFieldNombreUsuarioMousePressed(evt);
            }
        });
        txtFieldNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldNombreUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUsuarioLayout = new javax.swing.GroupLayout(panelUsuario);
        panelUsuario.setLayout(panelUsuarioLayout);
        panelUsuarioLayout.setHorizontalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFieldNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelUsuarioLayout.setVerticalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFieldNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelIngresar.setBackground(new java.awt.Color(226, 200, 204));
        panelIngresar.setRoundBottomLeft(20);
        panelIngresar.setRoundBottomRight(20);
        panelIngresar.setRoundTopLeft(20);
        panelIngresar.setRoundTopRight(20);

        lblRegistrarse.setBackground(new java.awt.Color(255, 255, 255));
        lblRegistrarse.setFont(new java.awt.Font("Burbank Big Cd Bd", 0, 24)); // NOI18N
        lblRegistrarse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistrarse.setText("REGISTRARSE");
        lblRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrarseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegistrarseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRegistrarseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelIngresarLayout = new javax.swing.GroupLayout(panelIngresar);
        panelIngresar.setLayout(panelIngresarLayout);
        panelIngresarLayout.setHorizontalGroup(
            panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 142, Short.MAX_VALUE)
        );
        panelIngresarLayout.setVerticalGroup(
            panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegistrarse, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        panelApellido.setBackground(new java.awt.Color(216, 152, 160));
        panelApellido.setRoundBottomLeft(20);
        panelApellido.setRoundBottomRight(20);
        panelApellido.setRoundTopLeft(20);
        panelApellido.setRoundTopRight(20);

        txtFieldApellido.setBackground(new java.awt.Color(216, 152, 160));
        txtFieldApellido.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        txtFieldApellido.setForeground(new java.awt.Color(204, 204, 204));
        txtFieldApellido.setText("Ingrese su apellido");
        txtFieldApellido.setBorder(null);
        txtFieldApellido.setSelectedTextColor(new java.awt.Color(204, 204, 255));
        txtFieldApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFieldApellidoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtFieldApellidoMousePressed(evt);
            }
        });
        txtFieldApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldApellidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelApellidoLayout = new javax.swing.GroupLayout(panelApellido);
        panelApellido.setLayout(panelApellidoLayout);
        panelApellidoLayout.setHorizontalGroup(
            panelApellidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelApellidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFieldApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelApellidoLayout.setVerticalGroup(
            panelApellidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelApellidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFieldApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblIngreseSuNombre.setFont(new java.awt.Font("Burbank Big Cd Bd", 0, 30)); // NOI18N
        lblIngreseSuNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIngreseSuNombre.setText("INGRESE SU NOMBRE:");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                        .addComponent(panelIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIngreseSuNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(panelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblIngreseSuApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(panelApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48))))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblIngreseSuNombre)
                .addGap(18, 18, 18)
                .addComponent(panelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblIngreseSuApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(209, 209, 209)
                .addComponent(panelIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        bg.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 460, 520));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("(REGISTRO)");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 460, -1));

        imgHamburguesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/hamburguesa.png"))); // NOI18N
        bg.add(imgHamburguesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, -1, -1));

        barraMovedora.setBackground(new java.awt.Color(160, 3, 23));
        barraMovedora.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraMovedoraMouseDragged(evt);
            }
        });
        barraMovedora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraMovedoraMousePressed(evt);
            }
        });

        javax.swing.GroupLayout barraMovedoraLayout = new javax.swing.GroupLayout(barraMovedora);
        barraMovedora.setLayout(barraMovedoraLayout);
        barraMovedoraLayout.setHorizontalGroup(
            barraMovedoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        barraMovedoraLayout.setVerticalGroup(
            barraMovedoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        bg.add(barraMovedora, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 40));

        panelExit.setBackground(new java.awt.Color(160, 3, 23));

        lblExit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setText("x");
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelExitLayout = new javax.swing.GroupLayout(panelExit);
        panelExit.setLayout(panelExitLayout);
        panelExitLayout.setHorizontalGroup(
            panelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblExit, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        panelExitLayout.setVerticalGroup(
            panelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(panelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 40, 40));

        lblCocosBurguer.setFont(new java.awt.Font("Comic Sans MS", 1, 30)); // NOI18N
        lblCocosBurguer.setForeground(new java.awt.Color(255, 255, 255));
        lblCocosBurguer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCocosBurguer.setText("COCO'S BURGUER");
        bg.add(lblCocosBurguer, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 460, -1));

        imgHamburguesa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/hamburguesa.png"))); // NOI18N
        bg.add(imgHamburguesa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        panelRegresar.setRoundBottomLeft(20);
        panelRegresar.setRoundBottomRight(20);
        panelRegresar.setRoundTopLeft(20);
        panelRegresar.setRoundTopRight(20);

        lblRegresar.setBackground(new java.awt.Color(255, 255, 255));
        lblRegresar.setFont(new java.awt.Font("Burbank Big Cd Bd", 0, 18)); // NOI18N
        lblRegresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegresar.setText("REGRESAR");
        lblRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRegresarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelRegresarLayout = new javax.swing.GroupLayout(panelRegresar);
        panelRegresar.setLayout(panelRegresarLayout);
        panelRegresarLayout.setHorizontalGroup(
            panelRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        panelRegresarLayout.setVerticalGroup(
            panelRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        bg.add(panelRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 130, 30));

        lblRegistrarse1.setBackground(new java.awt.Color(255, 255, 255));
        lblRegistrarse1.setFont(new java.awt.Font("Burbank Big Cd Bd", 0, 24)); // NOI18N
        lblRegistrarse1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistrarse1.setText("REGISTRARSE");
        lblRegistrarse1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRegistrarse1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrarse1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegistrarse1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRegistrarse1MouseExited(evt);
            }
        });
        bg.add(lblRegistrarse1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblRegistrarseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarseMouseEntered
        panelIngresar.setBackground(new Color(180,112,122));
        lblRegistrarse.setForeground(new Color(251,188,172));

    }//GEN-LAST:event_lblRegistrarseMouseEntered

    private void barraMovedoraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraMovedoraMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
           
    }//GEN-LAST:event_barraMovedoraMousePressed

    private void barraMovedoraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraMovedoraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_barraMovedoraMouseDragged

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        // TODO add your handling code here:
        panelExit.setBackground(new Color(251,40,67));
        lblExit.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        panelExit.setBackground(new Color(160,3,23));
        lblExit.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lblExitMouseExited

    private void lblRegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarseMouseClicked
        javax.swing.JOptionPane.showMessageDialog(this, "El administrador debe verificar esta cuenta");
            // Solicitar nombre de usuario para el administrador
        String adminNombre = JOptionPane.showInputDialog(this, "Ingrese su nombre de administrador:");

        // Crear un campo de contraseña para ocultar el texto ingresado
        JPasswordField adminPasswField = new JPasswordField();
        int option = JOptionPane.showConfirmDialog(this, adminPasswField, "Ingrese la contraseña del administrador:", JOptionPane.OK_CANCEL_OPTION);

        // Verificar que el usuario no haya cancelado en ningún paso
        if (option == JOptionPane.OK_OPTION) {
            String adminPassw = new String(adminPasswField.getPassword());

            // Verificar que ambos campos no estén vacíos o nulos
            if (adminNombre != null && !adminNombre.isEmpty() && !adminPassw.isEmpty()) {
                ArchivoPersonal ap=new ArchivoPersonal();
                Personal p= ap.buscarPersonalPorCredenciales(adminNombre, adminPassw);
                if("Administrador".equals(p.getRol())&&ap.verificarCredenciales(adminNombre, adminPassw)){
                    JOptionPane.showMessageDialog(this, "Cuenta verificada");
                    Cajero c= new Cajero(txtFieldNombreUsuario.getText(), txtFieldApellido.getText());
                    ap.agregarPersonal(c);
                    this.setVisible(false);
                    Menu objetoMenu = new Menu();
                    objetoMenu.setVisible(true);
                    
                }else{
                    JOptionPane.showMessageDialog(this, "No es una cuenta de administrador.");
                    
                }
                
            } else {
                JOptionPane.showMessageDialog(this, "Nombre de administrador o contraseña no pueden estar vacíos.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Verificación cancelada.");
        }
        
        
        //para obtener la contra:
        //String.valueOf(txtFieldPassword.getPassword());
    }//GEN-LAST:event_lblRegistrarseMouseClicked

    private void lblRegistrarseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarseMouseExited
        panelIngresar.setBackground(new Color(226,200,204));
        lblRegistrarse.setForeground(Color.black);
    }//GEN-LAST:event_lblRegistrarseMouseExited

    private void txtFieldNombreUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldNombreUsuarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldNombreUsuarioMouseClicked

    private void txtFieldNombreUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldNombreUsuarioMousePressed
        if(txtFieldNombreUsuario.getText().equals("Ingrese su nombre")){
             txtFieldNombreUsuario.setText("");
             txtFieldNombreUsuario.setForeground(Color.black);
        }
        if(txtFieldApellido.getText().equals("")){
             txtFieldApellido.setText("Ingrese su apellido");
             txtFieldApellido.setForeground(Color.gray);
        }
        
    }//GEN-LAST:event_txtFieldNombreUsuarioMousePressed

    private void txtFieldNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldNombreUsuarioActionPerformed

    private void txtFieldApellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldApellidoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldApellidoMouseClicked

    private void txtFieldApellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldApellidoMousePressed
        if(txtFieldNombreUsuario.getText().equals("")){
             txtFieldNombreUsuario.setText("Ingrese su nombre");
             txtFieldNombreUsuario.setForeground(Color.gray);
        }
        if(txtFieldApellido.getText().equals("Ingrese su apellido")){
             txtFieldApellido.setText("");
             txtFieldApellido.setForeground(Color.black);
        }
         
        
    }//GEN-LAST:event_txtFieldApellidoMousePressed

    private void txtFieldApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldApellidoActionPerformed

    private void lblRegistrarse1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarse1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRegistrarse1MouseClicked

    private void lblRegistrarse1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarse1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRegistrarse1MouseEntered

    private void lblRegistrarse1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarse1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRegistrarse1MouseExited

    private void lblRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegresarMouseClicked
        LoginV objetoLogin;
        objetoLogin = new LoginV();
        objetoLogin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblRegresarMouseClicked

    private void lblRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegresarMouseEntered
        lblRegresar.setForeground(Color.gray);
        panelRegresar.setBackground(Color.orange);
    }//GEN-LAST:event_lblRegresarMouseEntered

    private void lblRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegresarMouseExited
        lblRegresar.setForeground(Color.black);
        panelRegresar.setBackground(Color.white);
    }//GEN-LAST:event_lblRegresarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroCajeros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraMovedora;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel imgHamburguesa;
    private javax.swing.JLabel imgHamburguesa1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblCocosBurguer;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblIngreseSuApellido;
    private javax.swing.JLabel lblIngreseSuNombre;
    private javax.swing.JLabel lblRegistrarse;
    private javax.swing.JLabel lblRegistrarse1;
    private javax.swing.JLabel lblRegresar;
    private vista.PanelRound panelApellido;
    private javax.swing.JPanel panelExit;
    private vista.PanelRound panelIngresar;
    private vista.PanelRound panelRegresar;
    private vista.PanelRound panelRound1;
    private vista.PanelRound panelUsuario;
    private javax.swing.JTextField txtFieldApellido;
    private javax.swing.JTextField txtFieldNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
