/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Modelo.Producto;
import java.awt.Color;
import javax.swing.Icon;

/**
 *
 * @author Luis Bizarro
 */
public class Salchipapas extends javax.swing.JFrame {
    String categoria = "Salchipapas";
    String id="0";
    String nombre;
    double precio;
    int xMouse, yMouse;
    public Salchipapas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        imgLogoCocos = new javax.swing.JLabel();
        barraMovedora = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();
        panelExit = new javax.swing.JPanel();
        panelInicio = new javax.swing.JPanel();
        lblInicio = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        lblMenu = new javax.swing.JLabel();
        panelOrden = new javax.swing.JPanel();
        lblOrden = new javax.swing.JLabel();
        panelListaDeOrdenes = new javax.swing.JPanel();
        lblListaDeOrdenes = new javax.swing.JLabel();
        panelIniciarSesion = new javax.swing.JPanel();
        lblIniciarSesion = new javax.swing.JLabel();
        panelRound4 = new vista.PanelRound();
        lblSalchipapaDeshilachado = new javax.swing.JLabel();
        imgSalchipapaDeshilachado = new javax.swing.JLabel();
        pSDesilachado = new javax.swing.JLabel();
        pSSimple2 = new javax.swing.JLabel();
        pSSimple3 = new javax.swing.JLabel();
        pSSimple4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelRound8 = new vista.PanelRound();
        imgSalchipapaSimple = new javax.swing.JLabel();
        lblSalchipapaSimple1 = new javax.swing.JLabel();
        pSSimple1 = new javax.swing.JLabel();
        panelRound9 = new vista.PanelRound();
        lblSalchipapaChorizo = new javax.swing.JLabel();
        imgSalchipapaChorizo = new javax.swing.JLabel();
        pSChorizo = new javax.swing.JLabel();
        panelRound6 = new vista.PanelRound();
        lblSalchipapaRoyal = new javax.swing.JLabel();
        imgSalchipapaRoyal = new javax.swing.JLabel();
        pSRoyal = new javax.swing.JLabel();
        panelRound10 = new vista.PanelRound();
        lblSalchipapaPobre = new javax.swing.JLabel();
        imgSalchipapaPobre = new javax.swing.JLabel();
        pSPobre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(160, 3, 23));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgLogoCocos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/logoCocosBurger.png"))); // NOI18N
        bg.add(imgLogoCocos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        barraMovedora.setBackground(new java.awt.Color(160, 3, 23));
        barraMovedora.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraMovedoraMouseDragged(evt);
            }
        });
        barraMovedora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraMovedoraMousePressed(evt);
            }
        });

        javax.swing.GroupLayout barraMovedoraLayout = new javax.swing.GroupLayout(barraMovedora);
        barraMovedora.setLayout(barraMovedoraLayout);
        barraMovedoraLayout.setHorizontalGroup(
            barraMovedoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        barraMovedoraLayout.setVerticalGroup(
            barraMovedoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        bg.add(barraMovedora, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 30));

        lblExit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setText("x");
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });
        bg.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 40, 40));

        panelExit.setBackground(new java.awt.Color(160, 3, 23));

        javax.swing.GroupLayout panelExitLayout = new javax.swing.GroupLayout(panelExit);
        panelExit.setLayout(panelExitLayout);
        panelExitLayout.setHorizontalGroup(
            panelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        panelExitLayout.setVerticalGroup(
            panelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        bg.add(panelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 40, 40));

        panelInicio.setBackground(new java.awt.Color(160, 3, 23));

        lblInicio.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        lblInicio.setForeground(new java.awt.Color(255, 255, 255));
        lblInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInicio.setText("Inicio");
        lblInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblInicioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelInicioLayout = new javax.swing.GroupLayout(panelInicio);
        panelInicio.setLayout(panelInicioLayout);
        panelInicioLayout.setHorizontalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        panelInicioLayout.setVerticalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        bg.add(panelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 90, 50));

        panelMenu.setBackground(new java.awt.Color(160, 3, 23));

        lblMenu.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        lblMenu.setForeground(new java.awt.Color(255, 255, 255));
        lblMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenu.setText("Menu");
        lblMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMenuMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 100, -1));

        panelOrden.setBackground(new java.awt.Color(160, 3, 23));

        lblOrden.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        lblOrden.setForeground(new java.awt.Color(255, 255, 255));
        lblOrden.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrden.setText("Orden");
        lblOrden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOrdenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblOrdenMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelOrdenLayout = new javax.swing.GroupLayout(panelOrden);
        panelOrden.setLayout(panelOrdenLayout);
        panelOrdenLayout.setHorizontalGroup(
            panelOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblOrden, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        panelOrdenLayout.setVerticalGroup(
            panelOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOrdenLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(panelOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 110, -1));

        panelListaDeOrdenes.setBackground(new java.awt.Color(160, 3, 23));

        lblListaDeOrdenes.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        lblListaDeOrdenes.setForeground(new java.awt.Color(255, 255, 255));
        lblListaDeOrdenes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblListaDeOrdenes.setText("Lista de ordenes");
        lblListaDeOrdenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblListaDeOrdenesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblListaDeOrdenesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelListaDeOrdenesLayout = new javax.swing.GroupLayout(panelListaDeOrdenes);
        panelListaDeOrdenes.setLayout(panelListaDeOrdenesLayout);
        panelListaDeOrdenesLayout.setHorizontalGroup(
            panelListaDeOrdenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblListaDeOrdenes, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        panelListaDeOrdenesLayout.setVerticalGroup(
            panelListaDeOrdenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelListaDeOrdenesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblListaDeOrdenes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(panelListaDeOrdenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 190, -1));

        panelIniciarSesion.setBackground(new java.awt.Color(160, 3, 23));

        lblIniciarSesion.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        lblIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        lblIniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIniciarSesion.setText("Iniciar sesión");
        lblIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIniciarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIniciarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIniciarSesionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelIniciarSesionLayout = new javax.swing.GroupLayout(panelIniciarSesion);
        panelIniciarSesion.setLayout(panelIniciarSesionLayout);
        panelIniciarSesionLayout.setHorizontalGroup(
            panelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        panelIniciarSesionLayout.setVerticalGroup(
            panelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIniciarSesionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(panelIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, 150, -1));

        panelRound4.setBackground(new java.awt.Color(179, 53, 69));
        panelRound4.setRoundBottomLeft(20);
        panelRound4.setRoundBottomRight(20);
        panelRound4.setRoundTopLeft(20);
        panelRound4.setRoundTopRight(20);

        lblSalchipapaDeshilachado.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        lblSalchipapaDeshilachado.setForeground(new java.awt.Color(255, 255, 255));
        lblSalchipapaDeshilachado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalchipapaDeshilachado.setText("Salchipapa Deshilachado");
        lblSalchipapaDeshilachado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        imgSalchipapaDeshilachado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgSalchipapaDeshilachado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/imagenesProductos/Salchipapas/salchipapaConDeshilachado.png"))); // NOI18N
        imgSalchipapaDeshilachado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgSalchipapaDeshilachado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgSalchipapaDeshilachadoMouseClicked(evt);
            }
        });

        pSDesilachado.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        pSDesilachado.setForeground(new java.awt.Color(255, 255, 255));
        pSDesilachado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pSDesilachado.setText("14");
        pSDesilachado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pSSimple2.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        pSSimple2.setForeground(new java.awt.Color(255, 255, 255));
        pSSimple2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pSSimple2.setText("14");
        pSSimple2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pSSimple3.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        pSSimple3.setForeground(new java.awt.Color(255, 255, 255));
        pSSimple3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pSSimple3.setText("14");
        pSSimple3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pSSimple4.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        pSSimple4.setForeground(new java.awt.Color(255, 255, 255));
        pSSimple4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pSSimple4.setText("14");
        pSSimple4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSalchipapaDeshilachado, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
            .addComponent(imgSalchipapaDeshilachado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pSDesilachado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pSSimple2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pSSimple3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pSSimple4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgSalchipapaDeshilachado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSalchipapaDeshilachado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pSDesilachado, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pSSimple4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pSSimple3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pSSimple2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bg.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 230, 200));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SALCHIPAPAS");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 110, 730, -1));

        panelRound8.setBackground(new java.awt.Color(179, 53, 69));
        panelRound8.setRoundBottomLeft(20);
        panelRound8.setRoundBottomRight(20);
        panelRound8.setRoundTopLeft(20);
        panelRound8.setRoundTopRight(20);

        imgSalchipapaSimple.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgSalchipapaSimple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/imagenesProductos/Salchipapas/salchipapaSimple.png"))); // NOI18N
        imgSalchipapaSimple.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgSalchipapaSimple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgSalchipapaSimpleMouseClicked(evt);
            }
        });

        lblSalchipapaSimple1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        lblSalchipapaSimple1.setForeground(new java.awt.Color(255, 255, 255));
        lblSalchipapaSimple1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalchipapaSimple1.setText("Salchicha simple");
        lblSalchipapaSimple1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pSSimple1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        pSSimple1.setForeground(new java.awt.Color(255, 255, 255));
        pSSimple1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pSSimple1.setText("11");
        pSSimple1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelRound8Layout = new javax.swing.GroupLayout(panelRound8);
        panelRound8.setLayout(panelRound8Layout);
        panelRound8Layout.setHorizontalGroup(
            panelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound8Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblSalchipapaSimple1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(128, 128, 128))
            .addGroup(panelRound8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgSalchipapaSimple, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRound8Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(pSSimple1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(77, Short.MAX_VALUE)))
        );
        panelRound8Layout.setVerticalGroup(
            panelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgSalchipapaSimple, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(lblSalchipapaSimple1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(panelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound8Layout.createSequentialGroup()
                    .addContainerGap(179, Short.MAX_VALUE)
                    .addComponent(pSSimple1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(2, 2, 2)))
        );

        bg.add(panelRound8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 210, 210));

        panelRound9.setBackground(new java.awt.Color(179, 53, 69));
        panelRound9.setRoundBottomLeft(20);
        panelRound9.setRoundBottomRight(20);
        panelRound9.setRoundTopLeft(20);
        panelRound9.setRoundTopRight(20);

        lblSalchipapaChorizo.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        lblSalchipapaChorizo.setForeground(new java.awt.Color(255, 255, 255));
        lblSalchipapaChorizo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalchipapaChorizo.setText("Salchipapa Chorizo");
        lblSalchipapaChorizo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        imgSalchipapaChorizo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgSalchipapaChorizo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/imagenesProductos/Salchipapas/salchipapaConChorizo.png"))); // NOI18N
        imgSalchipapaChorizo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgSalchipapaChorizo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgSalchipapaChorizoMouseClicked(evt);
            }
        });

        pSChorizo.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        pSChorizo.setForeground(new java.awt.Color(255, 255, 255));
        pSChorizo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pSChorizo.setText("14");
        pSChorizo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelRound9Layout = new javax.swing.GroupLayout(panelRound9);
        panelRound9.setLayout(panelRound9Layout);
        panelRound9Layout.setHorizontalGroup(
            panelRound9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSalchipapaChorizo, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
            .addGroup(panelRound9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgSalchipapaChorizo, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addGroup(panelRound9Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(pSChorizo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelRound9Layout.setVerticalGroup(
            panelRound9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound9Layout.createSequentialGroup()
                .addComponent(imgSalchipapaChorizo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSalchipapaChorizo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pSChorizo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(panelRound9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 230, 210));

        panelRound6.setBackground(new java.awt.Color(179, 53, 69));
        panelRound6.setRoundBottomLeft(20);
        panelRound6.setRoundBottomRight(20);
        panelRound6.setRoundTopLeft(20);
        panelRound6.setRoundTopRight(20);

        lblSalchipapaRoyal.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        lblSalchipapaRoyal.setForeground(new java.awt.Color(255, 255, 255));
        lblSalchipapaRoyal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalchipapaRoyal.setText("Salchipapa Royal");
        lblSalchipapaRoyal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        imgSalchipapaRoyal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgSalchipapaRoyal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/imagenesProductos/Salchipapas/salchipapaRoyal.png"))); // NOI18N
        imgSalchipapaRoyal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgSalchipapaRoyal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgSalchipapaRoyalMouseClicked(evt);
            }
        });

        pSRoyal.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        pSRoyal.setForeground(new java.awt.Color(255, 255, 255));
        pSRoyal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pSRoyal.setText("14");
        pSRoyal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelRound6Layout = new javax.swing.GroupLayout(panelRound6);
        panelRound6.setLayout(panelRound6Layout);
        panelRound6Layout.setHorizontalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound6Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(pSRoyal, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelRound6Layout.createSequentialGroup()
                        .addGroup(panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imgSalchipapaRoyal, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(lblSalchipapaRoyal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        panelRound6Layout.setVerticalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgSalchipapaRoyal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSalchipapaRoyal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pSRoyal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(panelRound6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 230, 210));

        panelRound10.setBackground(new java.awt.Color(179, 53, 69));
        panelRound10.setRoundBottomLeft(20);
        panelRound10.setRoundBottomRight(20);
        panelRound10.setRoundTopLeft(20);
        panelRound10.setRoundTopRight(20);

        lblSalchipapaPobre.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        lblSalchipapaPobre.setForeground(new java.awt.Color(255, 255, 255));
        lblSalchipapaPobre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalchipapaPobre.setText("Salchipapa a lo pobre");
        lblSalchipapaPobre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        imgSalchipapaPobre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgSalchipapaPobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/imagenesProductos/Salchipapas/salchipapaPobre.png"))); // NOI18N
        imgSalchipapaPobre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgSalchipapaPobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgSalchipapaPobreMouseClicked(evt);
            }
        });

        pSPobre.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        pSPobre.setForeground(new java.awt.Color(255, 255, 255));
        pSPobre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pSPobre.setText("13");
        pSPobre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelRound10Layout = new javax.swing.GroupLayout(panelRound10);
        panelRound10.setLayout(panelRound10Layout);
        panelRound10Layout.setHorizontalGroup(
            panelRound10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSalchipapaPobre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelRound10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgSalchipapaPobre, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addGroup(panelRound10Layout.createSequentialGroup()
                        .addComponent(pSPobre, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelRound10Layout.setVerticalGroup(
            panelRound10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgSalchipapaPobre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSalchipapaPobre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pSPobre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(panelRound10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, -1, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barraMovedoraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraMovedoraMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
           
    }//GEN-LAST:event_barraMovedoraMousePressed

    private void barraMovedoraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraMovedoraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_barraMovedoraMouseDragged

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        // TODO add your handling code here:
        panelExit.setBackground(new Color(251,40,67));
        lblExit.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        panelExit.setBackground(new Color(160,3,23));
        lblExit.setForeground(Color.black);
    }//GEN-LAST:event_lblExitMouseExited

    private void lblInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInicioMouseEntered
        panelInicio.setBackground(new Color(108,2,16));
        lblInicio.setForeground(new Color(254,194,169));
    }//GEN-LAST:event_lblInicioMouseEntered

    private void lblInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInicioMouseExited
        panelInicio.setBackground(new Color(160,3,23));
        lblInicio.setForeground(Color.white);
    }//GEN-LAST:event_lblInicioMouseExited

    private void lblMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuMouseEntered
        panelMenu.setBackground(new Color(108,2,16));
        lblMenu.setForeground(new Color(254,194,169));
    }//GEN-LAST:event_lblMenuMouseEntered

    private void lblMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuMouseExited
        panelMenu.setBackground(new Color(160,3,23));
        lblMenu.setForeground(Color.white);
    }//GEN-LAST:event_lblMenuMouseExited

    private void lblOrdenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOrdenMouseEntered
        panelOrden.setBackground(new Color(108,2,16));
        lblOrden.setForeground(new Color(254,194,169));
    }//GEN-LAST:event_lblOrdenMouseEntered

    private void lblOrdenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOrdenMouseExited
        panelOrden.setBackground(new Color(160,3,23));
        lblOrden.setForeground(Color.white);
    }//GEN-LAST:event_lblOrdenMouseExited

    private void lblListaDeOrdenesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblListaDeOrdenesMouseEntered
        panelListaDeOrdenes.setBackground(new Color(108,2,16));
        lblListaDeOrdenes.setForeground(new Color(254,194,169));
    }//GEN-LAST:event_lblListaDeOrdenesMouseEntered

    private void lblListaDeOrdenesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblListaDeOrdenesMouseExited
        panelListaDeOrdenes.setBackground(new Color(160,3,23));
        lblListaDeOrdenes.setForeground(Color.white);
    }//GEN-LAST:event_lblListaDeOrdenesMouseExited

    private void lblIniciarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIniciarSesionMouseEntered
        panelIniciarSesion.setBackground(new Color(108,2,16));
        lblIniciarSesion.setForeground(new Color(254,194,169));
    }//GEN-LAST:event_lblIniciarSesionMouseEntered

    private void lblIniciarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIniciarSesionMouseExited
        panelIniciarSesion.setBackground(new Color(160,3,23));
        lblIniciarSesion.setForeground(Color.white);
    }//GEN-LAST:event_lblIniciarSesionMouseExited

    private void lblInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInicioMouseClicked
        Inicio objetoInicio = new Inicio();
        objetoInicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblInicioMouseClicked

    private void lblMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuMouseClicked
        Menu objetoMenu = new Menu();
        objetoMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblMenuMouseClicked

    private void lblIniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIniciarSesionMouseClicked
        LoginV objetoLogin = new LoginV();
        objetoLogin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblIniciarSesionMouseClicked

    private void imgSalchipapaSimpleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgSalchipapaSimpleMouseClicked
        // TODO add your handling code here:
        id="12";
        nombre = lblSalchipapaSimple1.getText();
        precio = Double.parseDouble(pSSimple1.getText());
        Producto sSimple = new Producto(id, nombre, precio, categoria);
        Icon iconoSSimple = imgSalchipapaSimple.getIcon();

        AgregadoDeCremas ventanaCremas = new AgregadoDeCremas(sSimple, iconoSSimple);
        ventanaCremas.setVisible(true);
        this.dispose();    
    }//GEN-LAST:event_imgSalchipapaSimpleMouseClicked

    private void imgSalchipapaDeshilachadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgSalchipapaDeshilachadoMouseClicked
        // TODO add your handling code here:
        id="13";
        nombre = lblSalchipapaDeshilachado.getText();
        precio = Double.parseDouble(pSDesilachado.getText());
        Producto sDeshilachado = new Producto(id, nombre, precio, categoria);
        Icon iconoSDeshilachado = imgSalchipapaDeshilachado.getIcon();

        AgregadoDeCremas ventanaCremas = new AgregadoDeCremas(sDeshilachado, iconoSDeshilachado);
        ventanaCremas.setVisible(true);
        this.dispose();   
    }//GEN-LAST:event_imgSalchipapaDeshilachadoMouseClicked

    private void imgSalchipapaChorizoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgSalchipapaChorizoMouseClicked
        // TODO add your handling code here:
        id="14";
        nombre = lblSalchipapaChorizo.getText();
        precio = Double.parseDouble(pSChorizo.getText());
        Producto SChorizo = new Producto(id, nombre, precio, categoria);
        Icon iconoSChorizo = imgSalchipapaChorizo.getIcon();

        AgregadoDeCremas ventanaCremas = new AgregadoDeCremas(SChorizo, iconoSChorizo);
        ventanaCremas.setVisible(true);
        this.dispose();  
    }//GEN-LAST:event_imgSalchipapaChorizoMouseClicked

    private void imgSalchipapaRoyalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgSalchipapaRoyalMouseClicked
        // TODO add your handling code here:
        id="15";
        nombre = lblSalchipapaRoyal.getText();
        precio = Double.parseDouble(pSRoyal.getText());
        Producto SRoyal = new Producto(id, nombre, precio, categoria);
        Icon iconoSRoyal = imgSalchipapaRoyal.getIcon();

        AgregadoDeCremas ventanaCremas = new AgregadoDeCremas(SRoyal, iconoSRoyal);
        ventanaCremas.setVisible(true);
        this.dispose();  
    }//GEN-LAST:event_imgSalchipapaRoyalMouseClicked

    private void imgSalchipapaPobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgSalchipapaPobreMouseClicked
        // TODO add your handling code here:
        id="16";
        nombre = lblSalchipapaPobre.getText();
        precio = Double.parseDouble(pSPobre.getText());
        Producto SPobre = new Producto(id, nombre, precio, categoria);
        Icon iconoSPobre = imgSalchipapaPobre.getIcon();

        AgregadoDeCremas ventanaCremas = new AgregadoDeCremas(SPobre, iconoSPobre);
        ventanaCremas.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_imgSalchipapaPobreMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Salchipapas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraMovedora;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel imgLogoCocos;
    private javax.swing.JLabel imgSalchipapaChorizo;
    private javax.swing.JLabel imgSalchipapaDeshilachado;
    private javax.swing.JLabel imgSalchipapaPobre;
    private javax.swing.JLabel imgSalchipapaRoyal;
    private javax.swing.JLabel imgSalchipapaSimple;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblIniciarSesion;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblListaDeOrdenes;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblOrden;
    private javax.swing.JLabel lblSalchipapaChorizo;
    private javax.swing.JLabel lblSalchipapaDeshilachado;
    private javax.swing.JLabel lblSalchipapaPobre;
    private javax.swing.JLabel lblSalchipapaRoyal;
    private javax.swing.JLabel lblSalchipapaSimple1;
    private javax.swing.JLabel pSChorizo;
    private javax.swing.JLabel pSDesilachado;
    private javax.swing.JLabel pSPobre;
    private javax.swing.JLabel pSRoyal;
    private javax.swing.JLabel pSSimple1;
    private javax.swing.JLabel pSSimple2;
    private javax.swing.JLabel pSSimple3;
    private javax.swing.JLabel pSSimple4;
    private javax.swing.JPanel panelExit;
    private javax.swing.JPanel panelIniciarSesion;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPanel panelListaDeOrdenes;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelOrden;
    private vista.PanelRound panelRound10;
    private vista.PanelRound panelRound4;
    private vista.PanelRound panelRound6;
    private vista.PanelRound panelRound8;
    private vista.PanelRound panelRound9;
    // End of variables declaration//GEN-END:variables
}
