/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Modelo.*;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis Bizarro
 */
public class VerTicket extends javax.swing.JFrame {
    private Pedido pedidoActual;
    int xMouse, yMouse;
    
    public VerTicket(Pedido pedido) {
        initComponents();
        this.pedidoActual = pedido;
        mostrarTicket();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        barraMovedora = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();
        panelExit = new javax.swing.JPanel();
        panelInicio = new javax.swing.JPanel();
        lblInicio = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        lblMenu = new javax.swing.JLabel();
        panelOrden = new javax.swing.JPanel();
        lblOrden = new javax.swing.JLabel();
        panelListaDeOrdenes = new javax.swing.JPanel();
        lblListaDeOrdenes = new javax.swing.JLabel();
        panelIniciarSesion = new javax.swing.JPanel();
        lblIniciarSesion = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelTicket = new vista.PanelRound();
        lblSeleccionado = new javax.swing.JLabel();
        numeroOrden = new javax.swing.JLabel();
        lblMenuSeleccionado = new javax.swing.JLabel();
        panelGenerarPedido = new vista.PanelRound();
        lblGenerarPedido = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblPrecioTotal = new javax.swing.JLabel();
        contenidoTicket = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(160, 3, 23));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/logoCocosBurger.png"))); // NOI18N
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        barraMovedora.setBackground(new java.awt.Color(160, 3, 23));
        barraMovedora.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraMovedoraMouseDragged(evt);
            }
        });
        barraMovedora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraMovedoraMousePressed(evt);
            }
        });

        javax.swing.GroupLayout barraMovedoraLayout = new javax.swing.GroupLayout(barraMovedora);
        barraMovedora.setLayout(barraMovedoraLayout);
        barraMovedoraLayout.setHorizontalGroup(
            barraMovedoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        barraMovedoraLayout.setVerticalGroup(
            barraMovedoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        bg.add(barraMovedora, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 30));

        lblExit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setText("x");
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });
        bg.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 40, 40));

        panelExit.setBackground(new java.awt.Color(160, 3, 23));

        javax.swing.GroupLayout panelExitLayout = new javax.swing.GroupLayout(panelExit);
        panelExit.setLayout(panelExitLayout);
        panelExitLayout.setHorizontalGroup(
            panelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        panelExitLayout.setVerticalGroup(
            panelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        bg.add(panelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 40, 40));

        panelInicio.setBackground(new java.awt.Color(160, 3, 23));

        lblInicio.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        lblInicio.setForeground(new java.awt.Color(255, 255, 255));
        lblInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInicio.setText("Inicio");
        lblInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblInicioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelInicioLayout = new javax.swing.GroupLayout(panelInicio);
        panelInicio.setLayout(panelInicioLayout);
        panelInicioLayout.setHorizontalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        panelInicioLayout.setVerticalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        bg.add(panelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 90, 50));

        panelMenu.setBackground(new java.awt.Color(160, 3, 23));

        lblMenu.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        lblMenu.setForeground(new java.awt.Color(255, 255, 255));
        lblMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenu.setText("Menu");
        lblMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMenuMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 100, -1));

        panelOrden.setBackground(new java.awt.Color(160, 3, 23));

        lblOrden.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        lblOrden.setForeground(new java.awt.Color(255, 255, 255));
        lblOrden.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrden.setText("Orden");
        lblOrden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOrdenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblOrdenMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelOrdenLayout = new javax.swing.GroupLayout(panelOrden);
        panelOrden.setLayout(panelOrdenLayout);
        panelOrdenLayout.setHorizontalGroup(
            panelOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblOrden, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        panelOrdenLayout.setVerticalGroup(
            panelOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOrdenLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(panelOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 110, -1));

        panelListaDeOrdenes.setBackground(new java.awt.Color(160, 3, 23));

        lblListaDeOrdenes.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        lblListaDeOrdenes.setForeground(new java.awt.Color(255, 255, 255));
        lblListaDeOrdenes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblListaDeOrdenes.setText("Lista de ordenes");
        lblListaDeOrdenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblListaDeOrdenesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblListaDeOrdenesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelListaDeOrdenesLayout = new javax.swing.GroupLayout(panelListaDeOrdenes);
        panelListaDeOrdenes.setLayout(panelListaDeOrdenesLayout);
        panelListaDeOrdenesLayout.setHorizontalGroup(
            panelListaDeOrdenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblListaDeOrdenes, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        panelListaDeOrdenesLayout.setVerticalGroup(
            panelListaDeOrdenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelListaDeOrdenesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblListaDeOrdenes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(panelListaDeOrdenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 190, -1));

        panelIniciarSesion.setBackground(new java.awt.Color(160, 3, 23));

        lblIniciarSesion.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        lblIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        lblIniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIniciarSesion.setText("Iniciar sesión");
        lblIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIniciarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIniciarSesionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelIniciarSesionLayout = new javax.swing.GroupLayout(panelIniciarSesion);
        panelIniciarSesion.setLayout(panelIniciarSesionLayout);
        panelIniciarSesionLayout.setHorizontalGroup(
            panelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        panelIniciarSesionLayout.setVerticalGroup(
            panelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIniciarSesionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(panelIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, 150, -1));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 1, 60)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Coco's");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Burguer");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        panelTicket.setRoundBottomLeft(20);
        panelTicket.setRoundBottomRight(20);
        panelTicket.setRoundTopLeft(20);
        panelTicket.setRoundTopRight(20);

        lblSeleccionado.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblSeleccionado.setText("Por pagar");

        numeroOrden.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        numeroOrden.setText("Orden N°20240101");

        lblMenuSeleccionado.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblMenuSeleccionado.setText("Detalles de la orden");

        panelGenerarPedido.setBackground(new java.awt.Color(255, 92, 40));
        panelGenerarPedido.setRoundBottomLeft(20);
        panelGenerarPedido.setRoundBottomRight(20);
        panelGenerarPedido.setRoundTopLeft(20);
        panelGenerarPedido.setRoundTopRight(20);

        lblGenerarPedido.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblGenerarPedido.setForeground(new java.awt.Color(255, 255, 255));
        lblGenerarPedido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGenerarPedido.setText("Generar pedido");
        lblGenerarPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblGenerarPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGenerarPedidoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelGenerarPedidoLayout = new javax.swing.GroupLayout(panelGenerarPedido);
        panelGenerarPedido.setLayout(panelGenerarPedidoLayout);
        panelGenerarPedidoLayout.setHorizontalGroup(
            panelGenerarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblGenerarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        panelGenerarPedidoLayout.setVerticalGroup(
            panelGenerarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblGenerarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel8.setText("Total");

        lblPrecioTotal.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblPrecioTotal.setText("S/.0.00");

        javax.swing.GroupLayout panelTicketLayout = new javax.swing.GroupLayout(panelTicket);
        panelTicket.setLayout(panelTicketLayout);
        panelTicketLayout.setHorizontalGroup(
            panelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTicketLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTicketLayout.createSequentialGroup()
                        .addComponent(contenidoTicket)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelTicketLayout.createSequentialGroup()
                        .addGroup(panelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMenuSeleccionado)
                            .addComponent(lblSeleccionado))
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(panelTicketLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPrecioTotal)
                        .addGap(43, 43, 43))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTicketLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelGenerarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
            .addGroup(panelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelTicketLayout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(numeroOrden)
                    .addContainerGap(231, Short.MAX_VALUE)))
        );
        panelTicketLayout.setVerticalGroup(
            panelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTicketLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(lblSeleccionado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMenuSeleccionado)
                .addGap(18, 18, 18)
                .addComponent(contenidoTicket)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblPrecioTotal))
                .addGap(15, 15, 15)
                .addComponent(panelGenerarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelTicketLayout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(numeroOrden)
                    .addContainerGap(386, Short.MAX_VALUE)))
        );

        bg.add(panelTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 420, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barraMovedoraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraMovedoraMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
           
    }//GEN-LAST:event_barraMovedoraMousePressed

    private void barraMovedoraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraMovedoraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_barraMovedoraMouseDragged

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        // TODO add your handling code here:
        panelExit.setBackground(new Color(251,40,67));
        lblExit.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        panelExit.setBackground(new Color(160,3,23));
        lblExit.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lblExitMouseExited

    private void lblInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInicioMouseEntered
        panelInicio.setBackground(new Color(108,2,16));
        lblInicio.setForeground(new Color(254,194,169));
    }//GEN-LAST:event_lblInicioMouseEntered

    private void lblInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInicioMouseExited
        panelInicio.setBackground(new Color(160,3,23));
        lblInicio.setForeground(Color.white);
    }//GEN-LAST:event_lblInicioMouseExited

    private void lblMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuMouseEntered
        panelMenu.setBackground(new Color(108,2,16));
        lblMenu.setForeground(new Color(254,194,169));
    }//GEN-LAST:event_lblMenuMouseEntered

    private void lblMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuMouseExited
        panelMenu.setBackground(new Color(160,3,23));
        lblMenu.setForeground(Color.white);
    }//GEN-LAST:event_lblMenuMouseExited

    private void lblOrdenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOrdenMouseEntered
        panelOrden.setBackground(new Color(108,2,16));
        lblOrden.setForeground(new Color(254,194,169));
    }//GEN-LAST:event_lblOrdenMouseEntered

    private void lblOrdenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOrdenMouseExited
        panelOrden.setBackground(new Color(160,3,23));
        lblOrden.setForeground(Color.white);
    }//GEN-LAST:event_lblOrdenMouseExited

    private void lblListaDeOrdenesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblListaDeOrdenesMouseEntered
        panelListaDeOrdenes.setBackground(new Color(108,2,16));
        lblListaDeOrdenes.setForeground(new Color(254,194,169));
    }//GEN-LAST:event_lblListaDeOrdenesMouseEntered

    private void lblListaDeOrdenesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblListaDeOrdenesMouseExited
        panelListaDeOrdenes.setBackground(new Color(160,3,23));
        lblListaDeOrdenes.setForeground(Color.white);
    }//GEN-LAST:event_lblListaDeOrdenesMouseExited

    private void lblIniciarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIniciarSesionMouseEntered
        panelIniciarSesion.setBackground(new Color(108,2,16));
        lblIniciarSesion.setForeground(new Color(254,194,169));
    }//GEN-LAST:event_lblIniciarSesionMouseEntered

    private void lblIniciarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIniciarSesionMouseExited
        panelIniciarSesion.setBackground(new Color(160,3,23));
        lblIniciarSesion.setForeground(Color.white);
    }//GEN-LAST:event_lblIniciarSesionMouseExited

    private void lblGenerarPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGenerarPedidoMouseClicked
        generarTicket();
        contenidoTicket.setText("");
        lblPrecioTotal.setText("");
        lblMenuSeleccionado.setText("");
        pedidoActual = null;
        new SplashScreen("src/vista/imagenes/ImagenesInicio/cargandoGIF.gif", 1000);
        Inicio vistaInicio = new Inicio();
        this.setVisible(false);
        vistaInicio.setVisible(true);
    }//GEN-LAST:event_lblGenerarPedidoMouseClicked

    private void mostrarTicket() {
        StringBuilder ticket = new StringBuilder();
        double sumaTotal = 0.0;
        numeroOrden.setText("Orden N°"+pedidoActual.getId());
        ticket.append("<html>");
        ticket.append("Pedido ID: ").append(pedidoActual.getId()).append("<br>");
        for (DetallePedido detalle : pedidoActual.getDetalles()) {
            ticket.append(detalle.toString()).append("<br>");
            sumaTotal += detalle.getProducto().getPrecio();
        }
        ticket.append("</html>");

        contenidoTicket.setText(ticket.toString());
        lblPrecioTotal.setText("Total: S/ " + sumaTotal);
    }


                                     
    private void generarTicket() {
        String ordenNumero = pedidoActual.getId();
        String menuSeleccionado = lblMenuSeleccionado.getText();
        String total = lblPrecioTotal.getText();
        String ticket = "Orden N°: " + ordenNumero + "\n" +
                        "Seleccionado: " + menuSeleccionado + "\n" +
                        "Total: " + total;
        JOptionPane.showMessageDialog(this, ticket, "Ticket de Pedido", JOptionPane.INFORMATION_MESSAGE);
        String filePath = "tickets.txt";
        pedidoActual.guardarEnArchivo(filePath);
    }
    
    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
    // Set look and feel for Nimbus theme
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        ex.printStackTrace();
    }

    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            Pedido pedidoActual = obtenerPedidoActual();
            if (pedidoActual != null) {
                new VerTicket(pedidoActual).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "No hay pedido actual.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    });
}

private static Pedido obtenerPedidoActual() {
    return ControladorPedido.getPedidoActual(); // Asumiendo que ControladorPedido tiene este método
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraMovedora;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel contenidoTicket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblGenerarPedido;
    private javax.swing.JLabel lblIniciarSesion;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblListaDeOrdenes;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblMenuSeleccionado;
    private javax.swing.JLabel lblOrden;
    private javax.swing.JLabel lblPrecioTotal;
    private javax.swing.JLabel lblSeleccionado;
    private javax.swing.JLabel numeroOrden;
    private javax.swing.JPanel panelExit;
    private vista.PanelRound panelGenerarPedido;
    private javax.swing.JPanel panelIniciarSesion;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPanel panelListaDeOrdenes;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelOrden;
    private vista.PanelRound panelTicket;
    // End of variables declaration//GEN-END:variables
}
